// 13 languages order: en, ar, es, fr, de, pt, ru, zh, ja, ko, tr, hi, it
// Each symbol: [en_t,en_h,en_m, ar_t,ar_h,ar_m, es..., it (13x3 = 39 strings)]
// NEW symbols not present in core SYM / batch2 / batch3.
export const BATCH4_SYMBOLS = {
  foot: [
    'Foot Dream Meaning', 'What Does It Mean to Dream About Feet?', 'Feet symbolize foundation, stability, and the path you walk through life.',
    'تفسير حلم القدم', 'ما معنى رؤية القدم في الحلم؟', 'القدم ترمز للأساس والاستقرار والطريق اللي بتمشي فيه حياتك.',
    'Soñar con pies', '¿Qué significa soñar con pies?', 'Los pies simbolizan la base y el camino de vida.',
    'Rêve de pieds', 'Que signifie rêver de pieds?', 'Les pieds symbolisent la fondation et le chemin.',
    'Füße im Traum', 'Was bedeutet Fuß im Traum?', 'Füße symbolisieren Grundlage und Lebensweg.',
    'Sonhar com pés', 'O que significa sonhar com pés?', 'Os pés representam a base e o caminho.',
    'Сон о ногах', 'Что значит сон о ногах?', 'Ноги символизируют основу и путь.',
    '梦见脚的含义', '梦见脚是什么意思？', '脚象征根基与人生之路。',
    '足の夢', '足の夢は何を意味する？', '足は基盤と人生の道を表す。',
    '발 꿈', '발 꿈은 무슨 의미일까?', '발은 기반과 삶의 길을 나타냅니다.',
    'Ayak rüyası', 'Ayak görmek ne anlama gelir?', 'Ayaklar temeli ve yaşam yolunu simgeler.',
    'पैर का सपना', 'सपने में पैर क्या मतलब?', 'पैर आधार और जीवन मार्ग का प्रतीक हैं।',
    'Sogno di piedi', 'Cosa significa sognare i piedi?', 'I piedi rappresentano la base e il cammino.',
  ],
  nose: [
    'Nose Dream Meaning', 'What Does It Mean to Dream About a Nose?', 'A nose symbolizes intuition, curiosity, and how you "sniff out" the truth.',
    'تفسير حلم الأنف', 'ما معنى رؤية الأنف في الحلم؟', 'الأنف يرمز للحدس والفضول وإحساسك بالحقيقة.',
    'Soñar con nariz', '¿Qué significa soñar con nariz?', 'La nariz simboliza intuición y curiosidad.',
    'Rêve de nez', 'Que signifie rêver de nez?', 'Le nez symbolise intuition et curiosité.',
    'Nase im Traum', 'Was bedeutet Nase im Traum?', 'Eine Nase symbolisiert Intuition und Neugier.',
    'Sonhar com nariz', 'O que significa sonhar com nariz?', 'O nariz representa intuição e curiosidade.',
    'Сон о носе', 'Что значит сон о носе?', 'Нос символизирует интуицию и любопытство.',
    '梦见鼻子的含义', '梦见鼻子是什么意思？', '鼻子象征直觉与好奇。',
    '鼻の夢', '鼻の夢は何を意味する？', '鼻は直感と好奇心を表す。',
    '코 꿈', '코 꿈은 무슨 의미일까?', '코는 직관과 호기심을 나타냅니다.',
    'Burun rüyası', 'Burun görmek ne anlama gelir?', 'Burun sezgiyi ve merakı simgeler.',
    'नाक का सपना', 'सपने में नाक क्या मतलब?', 'नाक अंतर्ज्ञान और जिज्ञासा का प्रतीक है।',
    'Sogno di naso', 'Cosa significa sognare il naso?', 'Il naso rappresenta intuizione e curiosità.',
  ],
  mouth: [
    'Mouth Dream Meaning', 'What Does It Mean to Dream About a Mouth?', 'A mouth symbolizes communication, expression, and words left unspoken.',
    'تفسير حلم الفم', 'ما معنى رؤية الفم في الحلم؟', 'الفم يرمز للتواصل والتعبير والكلمات اللي متقولتش.',
    'Soñar con boca', '¿Qué significa soñar con boca?', 'La boca simboliza comunicación y expresión.',
    'Rêve de bouche', 'Que signifie rêver de bouche?', 'La bouche symbolise communication et expression.',
    'Mund im Traum', 'Was bedeutet Mund im Traum?', 'Ein Mund symbolisiert Kommunikation und Ausdruck.',
    'Sonhar com boca', 'O que significa sonhar com boca?', 'A boca representa comunicação e expressão.',
    'Сон о рте', 'Что значит сон о рте?', 'Рот символизирует общение и выражение.',
    '梦见嘴巴的含义', '梦见嘴巴是什么意思？', '嘴巴象征沟通与表达。',
    '口の夢', '口の夢は何を意味する？', '口はコミュニケーションと表現を表す。',
    '입 꿈', '입 꿈은 무슨 의미일까?', '입은 소통과 표현을 나타냅니다.',
    'Ağız rüyası', 'Ağız görmek ne anlama gelir?', 'Ağız iletişimi ve ifadeyi simgeler.',
    'मुँह का सपना', 'सपने में मुँह क्या मतलब?', 'मुँह संचार और अभिव्यक्ति का प्रतीक है।',
    'Sogno di bocca', 'Cosa significa sognare la bocca?', 'La bocca rappresenta comunicazione ed espressione.',
  ],
  heart: [
    'Heart Dream Meaning', 'What Does It Mean to Dream About a Heart?', 'A heart symbolizes love, emotion, and the core of who you are.',
    'تفسير حلم القلب', 'ما معنى رؤية القلب في الحلم؟', 'القلب يرمز للحب والمشاعر ولبّ ذاتك.',
    'Soñar con corazón', '¿Qué significa soñar con corazón?', 'El corazón simboliza amor y emoción.',
    'Rêve de coeur', 'Que signifie rêver de coeur?', 'Le coeur symbolise amour et émotion.',
    'Herz im Traum', 'Was bedeutet Herz im Traum?', 'Ein Herz symbolisiert Liebe und Emotion.',
    'Sonhar com coração', 'O que significa sonhar com coração?', 'O coração representa amor e emoção.',
    'Сон о сердце', 'Что значит сон о сердце?', 'Сердце символизирует любовь и чувства.',
    '梦见心脏的含义', '梦见心脏是什么意思？', '心脏象征爱与情感。',
    '心の夢', '心の夢は何を意味する？', '心は愛と感情を表す。',
    '심장 꿈', '심장 꿈은 무슨 의미일까?', '심장은 사랑과 감정을 나타냅니다.',
    'Kalp rüyası', 'Kalp görmek ne anlama gelir?', 'Kalp sevgiyi ve duyguları simgeler.',
    'दिल का सपना', 'सपने में दिल क्या मतलब?', 'दिल प्यार और भावनाओं का प्रतीक है।',
    'Sogno di cuore', 'Cosa significa sognare il cuore?', 'Il cuore rappresenta amore ed emozione.',
  ],
  arm: [
    'Arm Dream Meaning', 'What Does It Mean to Dream About Arms?', 'Arms symbolize strength, support, and your capacity to embrace or defend.',
    'تفسير حلم الذراع', 'ما معنى رؤية الذراع في الحلم؟', 'الذراع يرمز للقوة والدعم وقدرتك على الاحتضان أو الدفاع.',
    'Soñar con brazos', '¿Qué significa soñar con brazos?', 'Los brazos simbolizan fuerza y apoyo.',
    'Rêve de bras', 'Que signifie rêver de bras?', 'Les bras symbolisent force et soutien.',
    'Arm im Traum', 'Was bedeutet Arm im Traum?', 'Arme symbolisieren Kraft und Halt.',
    'Sonhar com braços', 'O que significa sonhar com braços?', 'Os braços representam força e apoio.',
    'Сон о руках', 'Что значит сон о руках?', 'Руки символизируют силу и поддержку.',
    '梦见手臂的含义', '梦见手臂是什么意思？', '手臂象征力量与支持。',
    '腕の夢', '腕の夢は何を意味する？', '腕は力と支えを表す。',
    '팔 꿈', '팔 꿈은 무슨 의미일까?', '팔은 힘과 지지를 나타냅니다.',
    'Kol rüyası', 'Kol görmek ne anlama gelir?', 'Kollar gücü ve desteği simgeler.',
    'बाँह का सपना', 'सपने में बाँह क्या मतलब?', 'बाँह शक्ति और सहारे का प्रतीक है।',
    'Sogno di braccia', 'Cosa significa sognare le braccia?', 'Le braccia rappresentano forza e sostegno.',
  ],
  leg: [
    'Leg Dream Meaning', 'What Does It Mean to Dream About Legs?', 'Legs symbolize movement, progress, and your ability to stand on your own.',
    'تفسير حلم الساق', 'ما معنى رؤية الساق في الحلم؟', 'الساق يرمز للحركة والتقدم وقدرتك على الوقوف لوحدك.',
    'Soñar con piernas', '¿Qué significa soñar con piernas?', 'Las piernas simbolizan movimiento y progreso.',
    'Rêve de jambes', 'Que signifie rêver de jambes?', 'Les jambes symbolisent mouvement et progrès.',
    'Bein im Traum', 'Was bedeutet Bein im Traum?', 'Beine symbolisieren Bewegung und Fortschritt.',
    'Sonhar com pernas', 'O que significa sonhar com pernas?', 'As pernas representam movimento e progresso.',
    'Сон о ногах', 'Что значит сон о ногах?', 'Ноги символизируют движение и прогресс.',
    '梦见腿的含义', '梦见腿是什么意思？', '腿象征行动与进步。',
    '脚の夢', '脚の夢は何を意味する？', '脚は動きと進歩を表す。',
    '다리 꿈', '다리 꿈은 무슨 의미일까?', '다리는 움직임과 진보를 나타냅니다.',
    'Bacak rüyası', 'Bacak görmek ne anlama gelir?', 'Bacaklar hareketi ve ilerlemeyi simgeler.',
    'टाँग का सपना', 'सपने में टाँग क्या मतलब?', 'टाँगें गति और प्रगति का प्रतीक हैं।',
    'Sogno di gambe', 'Cosa significa sognare le gambe?', 'Le gambe rappresentano movimento e progresso.',
  ],
  king: [
    'King Dream Meaning', 'What Does It Mean to Dream About a King?', 'A king symbolizes authority, mastery, and the powerful part of your own psyche.',
    'تفسير حلم الملك', 'ما معنى رؤية الملك في الحلم؟', 'الملك يرمز للسلطة والسيادة والجزء القوي من نفسيتك.',
    'Soñar con rey', '¿Qué significa soñar con un rey?', 'El rey simboliza autoridad y poder.',
    'Rêve de roi', 'Que signifie rêver de roi?', 'Le roi symbolise autorité et pouvoir.',
    'König im Traum', 'Was bedeutet König im Traum?', 'Ein König symbolisiert Autorität und Macht.',
    'Sonhar com rei', 'O que significa sonhar com rei?', 'O rei representa autoridade e poder.',
    'Сон о короле', 'Что значит сон о короле?', 'Король символизирует власть и могущество.',
    '梦见国王的含义', '梦见国王是什么意思？', '国王象征权威与力量。',
    '王の夢', '王の夢は何を意味する？', '王は権威と力を表す。',
    '왕 꿈', '왕 꿈은 무슨 의미일까?', '왕은 권위와 힘을 나타냅니다.',
    'Kral rüyası', 'Kral görmek ne anlama gelir?', 'Kral otoriteyi ve gücü simgeler.',
    'राजा का सपना', 'सपने में राजा क्या मतलब?', 'राजा अधिकार और शक्ति का प्रतीक है।',
    'Sogno di re', 'Cosa significa sognare un re?', 'Il re rappresenta autorità e potere.',
  ],
  queen: [
    'Queen Dream Meaning', 'What Does It Mean to Dream About a Queen?', 'A queen symbolizes inner power, intuition, and the feminine force that rules your life.',
    'تفسير حلم الملكة', 'ما معنى رؤية الملكة في الحلم؟', 'الملكة ترمز للقوة الداخلية والحدس والقوة الأنثوية اللي تحكم حياتك.',
    'Soñar con reina', '¿Qué significa soñar con una reina?', 'La reina simboliza poder interior e intuición.',
    'Rêve de reine', 'Que signifie rêver de reine?', 'La reine symbolise pouvoir intérieur et intuition.',
    'Königin im Traum', 'Was bedeutet Königin im Traum?', 'Eine Königin symbolisiert innere Kraft und Intuition.',
    'Sonhar com rainha', 'O que significa sonhar com rainha?', 'A rainha representa poder interior e intuição.',
    'Сон о королеве', 'Что значит сон о королеве?', 'Королева символизирует внутреннюю силу и интуицию.',
    '梦见王后的含义', '梦见王后是什么意思？', '王后象征内在力量与直觉。',
    '女王の夢', '女王の夢は何を意味する？', '女王は内なる力と直感を表す。',
    '여왕 꿈', '여왕 꿈은 무슨 의미일까?', '여왕은 내면의 힘과 직관을 나타냅니다.',
    'Kraliçe rüyası', 'Kraliçe görmek ne anlama gelir?', 'Kraliçe içsel gücü ve sezgiyi simgeler.',
    'रानी का सपना', 'सपने में रानी क्या मतलब?', 'रानी आंतरिक शक्ति और अंतर्ज्ञान का प्रतीक है।',
    'Sogno di regina', 'Cosa significa sognare una regina?', 'La regina rappresenta forza interiore e intuizione.',
  ],
  bus: [
    'Bus Dream Meaning', 'What Does It Mean to Dream About a Bus?', 'A bus symbolizes a shared journey, routine, and where you feel you are being taken.',
    'تفسير حلم الباص', 'ما معنى رؤية الباص في الحلم؟', 'الباص يرمز لرحلة مشتركة وروتين ومكان اللي بتحس إنك رايحه.',
    'Soñar con autobús', '¿Qué significa soñar con un autobús?', 'El autobús simboliza un viaje compartido.',
    'Rêve de bus', 'Que signifie rêver de bus?', 'Le bus symbolise un trajet partagé.',
    'Bus im Traum', 'Was bedeutet Bus im Traum?', 'Ein Bus symbolisiert eine gemeinsame Reise.',
    'Sonhar com ônibus', 'O que significa sonhar com ônibus?', 'O ônibus representa viagem compartilhada.',
    'Сон об автобусе', 'Что значит сон об автобусе?', 'Автобус символизирует общую поездку.',
    '梦见公共汽车的含义', '梦见公共汽车是什么意思？', '公共汽车象征共同的旅程。',
    'バスの夢', 'バスの夢は何を意味する？', 'バスは共通の旅を表す。',
    '버스 꿈', '버스 꿈은 무슨 의미일까?', '버스는 함께하는 여정을 나타냅니다.',
    'Otobüs rüyası', 'Otobüs görmek ne anlama gelir?', 'Otobüs paylaşılan yolculuğu simgeler.',
    'बस का सपना', 'सपने में बस क्या मतलब?', 'बस साझा यात्रा का प्रतीक है।',
    'Sogno di autobus', 'Cosa significa sognare un autobus?', 'L’autobus rappresenta un viaggio condiviso.',
  ],
  motorcycle: [
    'Motorcycle Dream Meaning', 'What Does It Mean to Dream About a Motorcycle?', 'A motorcycle symbolizes freedom, risk, and solo momentum toward your goals.',
    'تفسير حلم الدراجة النارية', 'ما معنى رؤية الدراجة النارية في الحلم؟', 'الدراجة النارية ترمز للحرية والمخاطرة والزخم الفردي نحو أهدافك.',
    'Soñar con moto', '¿Qué significa soñar con moto?', 'La moto simboliza libertad y riesgo.',
    'Rêve de moto', 'Que signifie rêver de moto?', 'La moto symbolise liberté et risque.',
    'Motorrad im Traum', 'Was bedeutet Motorrad im Traum?', 'Ein Motorrad symbolisiert Freiheit und Risiko.',
    'Sonhar com moto', 'O que significa sonhar com moto?', 'A moto representa liberdade e risco.',
    'Сон о мотоцикле', 'Что значит сон о мотоцикле?', 'Мотоцикл символизирует свободу и риск.',
    '梦见摩托车的含义', '梦见摩托车是什么意思？', '摩托车象征自由与风险。',
    'バイクの夢', 'バイクの夢は何を意味する？', 'バイクは自由とリスクを表す。',
    '오토바이 꿈', '오토바이 꿈은 무슨 의미일까?', '오토바이는 자유와 위험을 나타냅니다.',
    'Motosiklet rüyası', 'Motosiklet görmek ne anlama gelir?', 'Motosiklet özgürlüğü ve riski simgeler.',
    'बाइक का सपना', 'सपने में बाइक क्या मतलब?', 'बाइक स्वतंत्रता और जोखिम का प्रतीक है।',
    'Sogno di moto', 'Cosa significa sognare una moto?', 'La moto rappresenta libertà e rischio.',
  ],
  market: [
    'Market Dream Meaning', 'What Does It Mean to Dream About a Market?', 'A market symbolizes choices, opportunity, and the value you place on things.',
    'تفسير حلم السوق', 'ما معنى رؤية السوق في الحلم؟', 'السوق يرمز للاختيارات والفرص والقيمة اللي بتديها للأشياء.',
    'Soñar con mercado', '¿Qué significa soñar con mercado?', 'El mercado simboliza elección y oportunidad.',
    'Rêve de marché', 'Que signifie rêver de marché?', 'Le marché symbolise choix et opportunité.',
    'Markt im Traum', 'Was bedeutet Markt im Traum?', 'Ein Markt symbolisiert Wahl und Chance.',
    'Sonhar com mercado', 'O que significa sonhar com mercado?', 'O mercado representa escolha e oportunidade.',
    'Сон о рынке', 'Что значит сон о рынке?', 'Рынок символизирует выбор и возможность.',
    '梦见市场的含义', '梦见市场是什么意思？', '市场象征选择与机会。',
    '市場の夢', '市場の夢は何を意味する？', '市場は選択と機会を表す。',
    '시장 꿈', '시장 꿈은 무슨 의미일까?', '시장은 선택과 기회를 나타냅니다.',
    'Pazar rüyası', 'Pazar görmek ne anlama gelir?', 'Pazar seçimi ve fırsatı simgeler.',
    'बाज़ार का सपना', 'सपने में बाज़ार क्या मतलब?', 'बाज़ार विकल्प और अवसर का प्रतीक है।',
    'Sogno di mercato', 'Cosa significa sognare un mercato?', 'Il mercato rappresenta scelta e opportunità.',
  ],
  clothes: [
    'Clothes Dream Meaning', 'What Does It Mean to Dream About Clothes?', 'Clothes symbolize identity, how you present yourself, and the role you play.',
    'تفسير حلم الملابس', 'ما معنى رؤية الملابس في الحلم؟', 'الملابس ترمز لهويتك وطريقة عرضك لنفسك والدور اللي بتلعبه.',
    'Soñar con ropa', '¿Qué significa soñar con ropa?', 'La ropa simboliza identidad y apariencia.',
    'Rêve de vêtements', 'Que signifie rêver de vêtements?', 'Les vêtements symbolisent identité et apparence.',
    'Kleidung im Traum', 'Was bedeutet Kleidung im Traum?', 'Kleidung symbolisiert Identität und Auftreten.',
    'Sonhar com roupas', 'O que significa sonhar com roupas?', 'As roupas representam identidade e aparência.',
    'Сон об одежде', 'Что значит сон об одежде?', 'Одежда символизирует личность и облик.',
    '梦见衣服的含义', '梦见衣服是什么意思？', '衣服象征身份与外在。',
    '服の夢', '服の夢は何を意味する？', '服はアイデンティティと外見を表す。',
    '옷 꿈', '옷 꿈은 무슨 의미일까?', '옷은 정체성과 외모를 나타냅니다.',
    'Kıyafet rüyası', 'Kıyafet görmek ne anlama gelir?', 'Kıyafet kimliği ve görünümü simgeler.',
    'कपड़ों का सपना', 'सपने में कपड़े क्या मतलब?', 'कपड़े पहचान और बाहरी रूप का प्रतीक हैं।',
    'Sogno di vestiti', 'Cosa significa sognare i vestiti?', 'I vestiti rappresentano identità e apparire.',
  ],
  shoe: [
    'Shoe Dream Meaning', 'What Does It Mean to Dream About Shoes?', 'Shoes symbolize your path, preparedness, and the direction you are walking.',
    'تفسير حلم الحذاء', 'ما معنى رؤية الحذاء في الحلم؟', 'الحذاء يرمز لطريقك وجاهزيتك والاتجاه اللي بتمشي فيه.',
    'Soñar con zapatos', '¿Qué significa soñar con zapatos?', 'Los zapatos simbolizan el camino y la preparación.',
    'Rêve de chaussures', 'Que signifie rêver de chaussures?', 'Les chaussures symbolisent le chemin et la préparation.',
    'Schuh im Traum', 'Was bedeutet Schuh im Traum?', 'Schuhe symbolisieren Weg und Vorbereitung.',
    'Sonhar com sapatos', 'O que significa sonhar com sapatos?', 'Os sapatos representam o caminho e a preparação.',
    'Сон об обуви', 'Что значит сон об обуви?', 'Обувь символизирует путь и готовность.',
    '梦见鞋子的含义', '梦见鞋子是什么意思？', '鞋子象征道路与准备。',
    '靴の夢', '靴の夢は何を意味する？', '靴は道と準備を表す。',
    '신발 꿈', '신발 꿈은 무슨 의미일까?', '신발은 길과 준비를 나타냅니다.',
    'Ayakkabı rüyası', 'Ayakkabı görmek ne anlama gelir?', 'Ayakkabı yolu ve hazırlığı simgeler.',
    'जूते का सपना', 'सपने में जूते क्या मतलब?', 'जूते रास्ते और तैयारी का प्रतीक हैं।',
    'Sogno di scarpe', 'Cosa significa sognare le scarpe?', 'Le scarpe rappresentano il cammino e la preparazione.',
  ],
  bag: [
    'Bag Dream Meaning', 'What Does It Mean to Dream About a Bag?', 'A bag symbolizes what you carry, your resources, and hidden concerns.',
    'تفسير حلم الحقيبة', 'ما معنى رؤية الحقيبة في الحلم؟', 'الحقيبة ترمز للي بتشيله ولمواردك ولهمومك المخفية.',
    'Soñar con bolso', '¿Qué significa soñar con bolso?', 'El bolso simboliza lo que llevas y tus recursos.',
    'Rêve de sac', 'Que signifie rêver de sac?', 'Le sac symbolise ce que vous portez et vos ressources.',
    'Tasche im Traum', 'Was bedeutet Tasche im Traum?', 'Eine Tasche symbolisiert das Mitgetragene und Ressourcen.',
    'Sonhar com bolsa', 'O que significa sonhar com bolsa?', 'A bolsa representa o que você carrega e seus recursos.',
    'Сон о сумке', 'Что значит сон о сумке?', 'Сумка символизирует то, что вы несёте, и ресурсы.',
    '梦见包的含义', '梦见包是什么意思？', '包象征你所承载的与资源。',
    '鞄の夢', '鞄の夢は何を意味する？', '鞄は持ち運ぶものと資源を表す。',
    '가방 꿈', '가방 꿈은 무슨 의미일까?', '가방은 짊어진 것과 자원을 나타냅니다.',
    'Çanta rüyası', 'Çanta görmek ne anlama gelir?', 'Çanta taşıdıklarınızı ve kaynakları simgeler.',
    'बैग का सपना', 'सपने में बैग क्या मतलब?', 'बैग आपके संसाधन और बोझ का प्रतीक है।',
    'Sogno di borsa', 'Cosa significa sognare una borsa?', 'La borsa rappresenta ciò che porti e le risorse.',
  ],
  wallet: [
    'Wallet Dream Meaning', 'What Does It Mean to Dream About a Wallet?', 'A wallet symbolizes self-worth, security, and how you manage your resources.',
    'تفسير حلم المحفظة', 'ما معنى رؤية المحفظة في الحلم؟', 'المحفظة ترمز لقيمتك الذاتية وأمانك وطريقة إدارتك لمواردك.',
    'Soñar con cartera', '¿Qué significa soñar con cartera?', 'La cartera simboliza autoestima y seguridad.',
    'Rêve de portefeuille', 'Que signifie rêver de portefeuille?', 'Le portefeuille symbolise estime de soi et sécurité.',
    'Brieftasche im Traum', 'Was bedeutet Brieftasche im Traum?', 'Eine Brieftasche symbolisiert Selbstwert und Sicherheit.',
    'Sonhar com carteira', 'O que significa sonhar com carteira?', 'A carteira representa autoestima e segurança.',
    'Сон о кошельке', 'Что значит сон о кошельке?', 'Кошелёк символизирует самооценку и безопасность.',
    '梦见钱包的含义', '梦见钱包是什么意思？', '钱包象征自我价值与安全。',
    '財布の夢', '財布の夢は何を意味する？', '財布は自己価値と安心を表す。',
    '지갑 꿈', '지갑 꿈은 무슨 의미일까?', '지갑은 자존감과 안전을 나타냅니다.',
    'Cüzdan rüyası', 'Cüzdan görmek ne anlama gelir?', 'Cüzdan öz değeri ve güvenliği simgeler.',
    'बटुए का सपना', 'सपने में बटुआ क्या मतलब?', 'बटुआ आत्म-मूल्य और सुरक्षा का प्रतीक है।',
    'Sogno di portafoglio', 'Cosa significa sognare un portafoglio?', 'Il portafoglio rappresenta autostima e sicurezza.',
  ],
  light: [
    'Light Dream Meaning', 'What Does It Mean to Dream About Light?', 'Light symbolizes clarity, hope, and sudden understanding breaking through darkness.',
    'تفسير حلم النور', 'ما معنى رؤية النور في الحلم؟', 'النور يرمز للوضوح والأمل والفهم اللي بيطلع من الظلام.',
    'Soñar con luz', '¿Qué significa soñar con luz?', 'La luz simboliza claridad y esperanza.',
    'Rêve de lumière', 'Que signifie rêver de lumière?', 'La lumière symbolise clarté et espoir.',
    'Licht im Traum', 'Was bedeutet Licht im Traum?', 'Licht symbolisiert Klarheit und Hoffnung.',
    'Sonhar com luz', 'O que significa sonhar com luz?', 'A luz representa clareza e esperança.',
    'Сон о свете', 'Что значит сон о свете?', 'Свет символизирует ясность и надежду.',
    '梦见光明的含义', '梦见光明是什么意思？', '光明象征清晰与希望。',
    '光の夢', '光の夢は何を意味する？', '光は明晰さと希望を表す。',
    '빛 꿈', '빛 꿈은 무슨 의미일까?', '빛은 명확함과 희망을 나타냅니다.',
    'Işık rüyası', 'Işık görmek ne anlama gelir?', 'Işık netliği ve umudu simgeler.',
    'प्रकाश का सपना', 'सपने में प्रकाश क्या मतलब?', 'प्रकाश स्पष्टता और आशा का प्रतीक है।',
    'Sogno di luce', 'Cosa significa sognare la luce?', 'La luce rappresenta chiarezza e speranza.',
  ],
  dark: [
    'Dark Dream Meaning', 'What Does It Mean to Dream About Darkness?', 'Darkness symbolizes the unknown, fear, and parts of yourself not yet revealed.',
    'تفسير حلم الظلام', 'ما معنى رؤية الظلام في الحلم؟', 'الظلام يرمز للمجهول والخوف ولأجزاء منك لسه ما ظهرتش.',
    'Soñar con oscuridad', '¿Qué significa soñar con oscuridad?', 'La oscuridad simboliza lo desconocido y el miedo.',
    'Rêve d’obscurité', 'Que signifie rêver d’obscurité?', 'L’obscurité symbolise l’inconnu et la peur.',
    'Dunkelheit im Traum', 'Was bedeutet Dunkelheit im Traum?', 'Dunkelheit symbolisiert Unbekanntes und Angst.',
    'Sonhar com escuridão', 'O que significa sonhar com escuridão?', 'A escuridão representa o desconhecido e o medo.',
    'Сон о тьме', 'Что значит сон о тьме?', 'Тьма символизирует неизвестное и страх.',
    '梦见黑暗的含义', '梦见黑暗是什么意思？', '黑暗象征未知与恐惧。',
    '暗闇の夢', '暗闇の夢は何を意味する？', '暗闇は未知と恐怖を表す。',
    '어둠 꿈', '어둠 꿈은 무슨 의미일까?', '어둠은 미지와 두려움을 나타냅니다.',
    'Karanlık rüyası', 'Karanlık görmek ne anlama gelir?', 'Karanlık bilinmeyeni ve korkuyu simgeler.',
    'अंधेरे का सपना', 'सपने में अंधेरा क्या मतलब?', 'अंधेरा अज्ञात और भय का प्रतीक है।',
    'Sogno di oscurità', 'Cosa significa sognare l’oscurità?', 'L’oscurità rappresenta l’ignoto e la paura.',
  ],
  smoke: [
    'Smoke Dream Meaning', 'What Does It Mean to Dream About Smoke?', 'Smoke symbolizes confusion, warning, and something hidden behind the surface.',
    'تفسير حلم الدخان', 'ما معنى رؤية الدخان في الحلم؟', 'الدخان يرمز للبلبة والتحذير ولشيء متخفي وراء السطح.',
    'Soñar con humo', '¿Qué significa soñar con humo?', 'El humo simboliza confusión y advertencia.',
    'Rêve de fumée', 'Que signifie rêver de fumée?', 'La fumée symbolise confusion et avertissement.',
    'Rauch im Traum', 'Was bedeutet Rauch im Traum?', 'Rauch symbolisiert Verwirrung und Warnung.',
    'Sonhar com fumaça', 'O que significa sonhar com fumaça?', 'A fumaça representa confusão e aviso.',
    'Сон о дыме', 'Что значит сон о дыме?', 'Дым символизирует замешательство и предупреждение.',
    '梦见烟的含义', '梦见烟是什么意思？', '烟象征混乱与警示。',
    '煙の夢', '煙の夢は何を意味する？', '煙は混乱と警告を表す。',
    '연기 꿈', '연기 꿈은 무슨 의미일까?', '연기는 혼란과 경고를 나타냅니다.',
    'Duman rüyası', 'Duman görmek ne anlama gelir?', 'Duman kafa karışıklığını ve uyarısı simgeler.',
    'धुएँ का सपना', 'सपने में धुआँ क्या मतलब?', 'धुआँ भ्रम और चेतावनी का प्रतीक है।',
    'Sogno di fumo', 'Cosa significa sognare il fumo?', 'Il fumo rappresenta confusione e avvertimento.',
  ],
  desert: [
    'Desert Dream Meaning', 'What Does It Mean to Dream About a Desert?', 'A desert symbolizes emptiness, solitude, and a need to find what truly nourishes you.',
    'تفسير حلم الصحراء', 'ما معنى رؤية الصحراء في الحلم؟', 'الصحراء ترمز للفراغ والوحدة ولحاجتك تلاقي اللي يغذيك فعلاً.',
    'Soñar con desierto', '¿Qué significa soñar con desierto?', 'El desierto simboliza vacío y soledad.',
    'Rêve de désert', 'Que signifie rêver de désert?', 'Le désert symbolise vide et solitude.',
    'Wüste im Traum', 'Was bedeutet Wüste im Traum?', 'Eine Wüste symbolisiert Leere und Einsamkeit.',
    'Sonhar com deserto', 'O que significa sonhar com deserto?', 'O deserto representa vazio e solidão.',
    'Сон о пустыне', 'Что значит сон о пустыне?', 'Пустыня символизирует пустоту и одиночество.',
    '梦见沙漠的含义', '梦见沙漠是什么意思？', '沙漠象征空虚与孤独。',
    '砂漠の夢', '砂漠の夢は何を意味する？', '砂漠は虚無と孤独を表す。',
    '사막 꿈', '사막 꿈은 무슨 의미일까?', '사막은 공허와 고독을 나타냅니다.',
    'Çöl rüyası', 'Çöl görmek ne anlama gelir?', 'Çöl boşluğu ve yalnızlığı simgeler.',
    'रेगिस्तान का सपना', 'सपने में रेगिस्तान क्या मतलब?', 'रेगिस्तान शून्यता और अकेलेपन का प्रतीक है।',
    'Sogno di deserto', 'Cosa significa sognare il deserto?', 'Il deserto rappresenta vuoto e solitudine.',
  ],
  ocean: [
    'Ocean Dream Meaning', 'What Does It Mean to Dream About the Ocean?', 'The ocean symbolizes the vast unconscious, deep emotion, and infinite possibility.',
    'تفسير حلم المحيط', 'ما معنى رؤية المحيط في الحلم؟', 'المحيط يرمز لللاوعي الواسع والعاطفة العميقة والاحتمالات اللانهائية.',
    'Soñar con océano', '¿Qué significa soñar con océano?', 'El océano simboliza el inconsciente vasto.',
    'Rêve d’océan', 'Que signifie rêver d’océan?', 'L’océan symbolise l’inconscient vaste.',
    'Ozean im Traum', 'Was bedeutet Ozean im Traum?', 'Ein Ozean symbolisiert das weite Unbewusste.',
    'Sonhar com oceano', 'O que significa sonhar com oceano?', 'O oceano representa o inconsciente vasto.',
    'Сон об океане', 'Что значит сон об океане?', 'Океан символизирует обширное подсознание.',
    '梦见海洋的含义', '梦见海洋是什么意思？', '海洋象征广阔的潜意识。',
    '海の夢', '海の夢は何を意味する？', '海は広大な無意識を表す。',
    '바다 꿈', '바다 꿈은 무슨 의미일까?', '바다는 광대한 무의식을 나타냅니다.',
    'Okyanus rüyası', 'Okyanus görmek ne anlama gelir?', 'Okyanus geniş bilinçdışını simgeler.',
    'महासागर का सपना', 'सपने में महासागर क्या मतलब?', 'महासागर विस्तृत अचेतन का प्रतीक है।',
    'Sogno di oceano', 'Cosa significa sognare l’oceano?', 'L’oceano rappresenta l’inconscio vasto.',
  ],
  ambulance: [
    'Ambulance Dream Meaning', 'What Does It Mean to Dream About an Ambulance?', 'An ambulance symbolizes urgency, rescue, and a need for healing or help.',
    'تفسير حلم الإسعاف', 'ما معنى رؤية الإسعاف في الحلم؟', 'الإسعاف يرمز للاستعجال والإنقاذ واحتياجك للشفاء أو المساعدة.',
    'Soñar con ambulancia', '¿Qué significa soñar con ambulancia?', 'La ambulancia simboliza urgencia y rescate.',
    'Rêve d’ambulance', 'Que signifie rêver d’ambulance?', 'L’ambulance symbolise urgence et secours.',
    'Krankenwagen im Traum', 'Was bedeutet Krankenwagen im Traum?', 'Ein Krankenwagen symbolisiert Dringlichkeit und Rettung.',
    'Sonhar com ambulância', 'O que significa sonhar com ambulância?', 'A ambulância representa urgência e resgate.',
    'Сон о скорой помощи', 'Что значит сон о скорой помощи?', 'Скорая помощь символизирует срочность и спасение.',
    '梦见救护车的含义', '梦见救护车是什么意思？', '救护车象征紧急与救援。',
    '救急車の夢', '救急車の夢は何を意味する？', '救急車は緊急性と救助を表す。',
    '구급차 꿈', '구급차 꿈은 무슨 의미일까?', '구급차는 긴급함과 구조를 나타냅니다.',
    'Ambulans rüyası', 'Ambulans görmek ne anlama gelir?', 'Ambulans aciliyeti ve kurtuluşu simgeler.',
    'एम्बुलेंस का सपना', 'सपने में एम्बुलेंस क्या मतलब?', 'एम्बुलेंस तात्कालिकता और बचाव का प्रतीक है।',
    'Sogno di ambulanza', 'Cosa significa sognare l’ambulanza?', 'L’ambulanza rappresenta urgenza e soccorso.',
  ],
};
