// Batch 2 symbols: [sk, [en_t,en_h,en_m, ar,es,fr,de,pt,ru,zh,ja,ko,tr,hi,it (each t,h,m)]]
// 13 languages order: en, ar, es, fr, de, pt, ru, zh, ja, ko, tr, hi, it
export const BATCH2_SYMBOLS = {
  food: [
    'Food Dream Meaning', 'What Does It Mean to Dream About Food?', 'Food in dreams represents nourishment, desires, and emotional satisfaction.',
    'تفسير حلم الأكل', 'ما معنى رؤية الأكل في الحلم؟', 'الأكل في الحلم يرمز للرزق والشهوات والإشباع العاطفي.',
    'Soñar con comida', '¿Qué significa soñar con comida?', 'La comida representa nutrición y deseos.',
    'Rêve de nourriture', 'Que signifie rêver de nourriture?', 'La nourriture représente le soutien et les désirs.',
    'Essen im Traum', 'Was bedeutet Essen im Traum?', 'Essen symbolisiert Nahrung und Begierden.',
    'Sonhar com comida', 'O que significa sonhar com comida?', 'Comida representa nutrição e desejos.',
    'Сон о еде', 'Что значит сон о еде?', 'Еда символизирует питание и желания.',
    '梦见食物的含义', '梦见食物是什么意思？', '食物代表滋养与渴望。',
    '食べ物の夢', '食べ物の夢は何を意味する？', '食べ物は養いと欲望を表す。',
    '음식 꿈 해몽', '음식 꿈은 무슨 의미일까?', '음식은 양분과 욕망을 나타냅니다.',
    'Yemek rüyası', 'Yemek görmek ne anlama gelir?', 'Yemek beslenmeyi ve arzuları simgeler.',
    'खाने का सपना', 'सपने में खाना क्या मतलब?', 'खाना पोषण और इच्छाओं का प्रतीक है।',
    'Sogno di cibo', 'Cosa significa sognare cibo?', 'Il cibo rappresenta nutrimento e desideri.',
  ],
  car: [
    'Car Dream Meaning', 'What Does It Mean to Dream About a Car?', 'A car represents your life path, control, and direction. Driving smoothly suggests confidence.',
    'تفسير حلم السيارة', 'ما معنى رؤية السيارة في الحلم؟', 'السيارة تمثل مسار حياتك والسيطرة والاتجاه.',
    'Soñar con coche', '¿Qué significa soñar con un coche?', 'El coche representa tu camino de vida.',
    'Rêve de voiture', 'Que signifie rêver de voiture?', 'La voiture représente votre parcours.',
    'Autotraum', 'Was bedeutet Autotraum?', 'Ein Auto symbolisiert Lebensweg und Kontrolle.',
    'Sonhar com carro', 'O que significa sonhar com carro?', 'O carro representa o caminho da vida.',
    'Сон о машине', 'Что значит сон о машине?', 'Машина символизирует жизненный путь.',
    '梦见汽车的含义', '梦见汽车是什么意思？', '汽车代表人生方向与掌控。',
    '車の夢', '車の夢は何を意味する？', '車は人生の道筋を表す。',
    '차 꿈 해몽', '차 꿈은 무슨 의미일까?', '차는 인생의 길과 통제를 나타냅니다.',
    'Araba rüyası', 'Araba görmek ne anlama gelir?', 'Araba yaşam yolunuzu simgeler.',
    'कार का सपना', 'सपने में कार क्या मतलब?', 'कार जीवन की दिशा और नियंत्रण है।',
    'Sogno di automobile', 'Cosa significa sognare un automobile?', 'L\'auto rappresenta il percorso di vita.',
  ],
  rain: [
    'Rain Dream Meaning', 'What Does It Mean to Dream About Rain?', 'Rain symbolizes cleansing, renewal, and emotional release. Gentle rain brings calm.',
    'تفسير حلم المطر', 'ما معنى رؤية المطر في الحلم؟', 'المطر يرمز للتطهير والتجدد والانطلاق العاطفي.',
    'Soñar con lluvia', '¿Qué significa soñar con lluvia?', 'La lluvia representa renovación.',
    'Rêve de pluie', 'Que signifie rêver de pluie?', 'La pluie représente le renouveau.',
    'Regen im Traum', 'Was bedeutet Regen im Traum?', 'Regen symbolisiert Reinigung und Erneuerung.',
    'Sonhar com chuva', 'O que significa sonhar com chuva?', 'A chuva representa renovação.',
    'Сон о дожде', 'Что значит сон о дожде?', 'Дождь символизирует очищение.',
    '梦见雨的含义', '梦见雨是什么意思？', '雨代表净化与更新。',
    '雨の夢', '雨の夢は何を意味する？', '雨は浄化と再生を表す。',
    '비 꿈 해몽', '비 꿈은 무슨 의미일까?', '비는 정화와 재생을 나타냅니다.',
    'Yağmur rüyası', 'Yağmur görmek ne anlama gelir?', 'Yağmur yenilenmeyi simgeler.',
    'बारिश का सपना', 'सपने में बारिश क्या मतलब?', 'बारिश शुद्धिकरण और नवीनीकरण है।',
    'Sogno di pioggia', 'Cosa significa sognare pioggia?', 'La pioggia rappresenta rinnovamento.',
  ],
  storm: [
    'Storm Dream Meaning', 'What Does It Mean to Dream About a Storm?', 'A storm represents turmoil, sudden change, and suppressed emotions rising to the surface.',
    'تفسير حلم العاصفة', 'ما معنى رؤية العاصفة في الحلم؟', 'العاصفة ترمز للاضطراب والتغيير المفاجئ.',
    'Soñar con tormenta', '¿Qué significa soñar con tormenta?', 'La tormenta representa turbulencia.',
    'Rêve d\'orage', 'Que signifie rêver d\'orage?', 'L\'orage représente le tumulte.',
    'Sturm im Traum', 'Was bedeutet Sturm im Traum?', 'Ein Sturm symbolisiert Aufruhr.',
    'Sonhar com tempestade', 'O que significa sonhar com tempestade?', 'A tempestade representa turbulência.',
    'Сон о буре', 'Что значит сон о буре?', 'Буря символизирует смятение.',
    '梦见暴风雨的含义', '梦见暴风雨是什么意思？', '暴风雨代表动荡与突变。',
    '嵐の夢', '嵐の夢は何を意味する？', '嵐は動乱を表す。',
    '폭풍 꿈 해몽', '폭풍 꿈은 무슨 의미일까?', '폭풍은 혼란을 나타냅니다.',
    'Fırtına rüyası', 'Fırtına görmek ne anlama gelir?', 'Fırtına kargaşayı simgeler.',
    'तूफान का सपना', 'सपने में तूफान क्या मतलब?', 'तूफान उथल-पुथल का प्रतीक है।',
    'Sogno di tempesta', 'Cosa significa sognare tempesta?', 'La tempesta rappresenta il tumulto.',
  ],
  gold: [
    'Gold Dream Meaning', 'What Does It Mean to Dream About Gold?', 'Gold symbolizes value, success, and spiritual wealth. Finding gold suggests reward.',
    'تفسير حلم الذهب', 'ما معنى رؤية الذهب في الحلم؟', 'الذهب يرمز للقيمة والنجاح والغنى الروحي.',
    'Soñar con oro', '¿Qué significa soñar con oro?', 'El oro representa valor y éxito.',
    'Rêve d\'or', 'Que signifie rêver d\'or?', 'L\'or représente la valeur et le succès.',
    'Gold im Traum', 'Was bedeutet Gold im Traum?', 'Gold symbolisiert Wert und Erfolg.',
    'Sonhar com ouro', 'O que significa sonhar com ouro?', 'O ouro representa valor e sucesso.',
    'Сон о золоте', 'Что значит сон о золоте?', 'Золото символизирует ценность.',
    '梦见黄金的含义', '梦见黄金是什么意思？', '黄金代表价值与成功。',
    '金の夢', '金の夢は何を意味する？', '金は価値と成功を表す。',
    '금 꿈 해몽', '금 꿈은 무슨 의미일까?', '금은 가치와 성공을 나타냅니다.',
    'Altın rüyası', 'Altın görmek ne anlama gelir?', 'Altın değer ve başarıyı simgeler.',
    'सोने का सपना', 'सपने में सोना क्या मतलब?', 'सोना मूल्य और सफलता का प्रतीक है।',
    'Sogno d\'oro', 'Cosa significa sognare oro?', 'L\'oro rappresenta valore e successo.',
  ],
  book: [
    'Book Dream Meaning', 'What Does It Mean to Dream About a Book?', 'A book represents knowledge, hidden truths, and a chapter of your life.',
    'تفسير حلم الكتاب', 'ما معنى رؤية الكتاب في الحلم؟', 'الكتاب يرمز للمعرفة والحقائق الخفية.',
    'Soñar con libro', '¿Qué significa soñar con libro?', 'El libro representa conocimiento.',
    'Rêve de livre', 'Que signifie rêver de livre?', 'Le livre représente la connaissance.',
    'Buch im Traum', 'Was bedeutet Buch im Traum?', 'Ein Buch symbolisiert Wissen.',
    'Sonhar com livro', 'O que significa sonhar com livro?', 'O livro representa conhecimento.',
    'Сон о книге', 'Что значит сон о книге?', 'Книга символизирует знание.',
    '梦见书的含义', '梦见书是什么意思？', '书代表知识与真理。',
    '本の夢', '本の夢は何を意味する？', '本は知識を表す。',
    '책 꿈 해몽', '책 꿈은 무슨 의미일까?', '책은 지식과 진실을 나타냅니다.',
    'Kitap rüyası', 'Kitap görmek ne anlama gelir?', 'Kitap bilgiyi simgeler.',
    'किताब का सपना', 'सपने में किताब क्या मतलब?', 'किताब ज्ञान का प्रतीक है।',
    'Sogno di libro', 'Cosa significa sognare libro?', 'Il libro rappresenta la conoscenza.',
  ],
  door: [
    'Door Dream Meaning', 'What Does It Mean to Dream About a Door?', 'A door symbolizes opportunity, transition, and new beginnings. An open door invites change.',
    'تفسير حلم الباب', 'ما معنى رؤية الباب في الحلم؟', 'الباب يرمز للفرصة والانتقال والبدايات الجديدة.',
    'Soñar con puerta', '¿Qué significa soñar con puerta?', 'La puerta representa oportunidad.',
    'Rêve de porte', 'Que signifie rêver de porte?', 'La porte représente l\'opportunité.',
    'Tür im Traum', 'Was bedeutet Tür im Traum?', 'Eine Tür symbolisiert eine Chance.',
    'Sonhar com porta', 'O que significa sonhar com porta?', 'A porta representa oportunidade.',
    'Сон о двери', 'Что значит сон о двери?', 'Дверь символизирует возможность.',
    '梦见门的含义', '梦见门是什么意思？', '门代表机会与转变。',
    'ドアの夢', 'ドアの夢は何を意味する？', 'ドアは機会を表す。',
    '문 꿈 해몽', '문 꿈은 무슨 의미일까?', '문은 기회와 전환을 나타냅니다.',
    'Kapı rüyası', 'Kapı görmek ne anlama gelir?', 'Kapı fırsatı simgeler.',
    'दरवाजे का सपना', 'सपने में दरवाजा क्या मतलब?', 'दरवाजा अवसर का प्रतीक है।',
    'Sogno di porta', 'Cosa significa sognare porta?', 'La porta rappresenta l\'opportunità.',
  ],
  key: [
    'Key Dream Meaning', 'What Does It Mean to Dream About a Key?', 'A key represents access, solutions, and unlocking potential. Losing a key suggests anxiety.',
    'تفسير حلم المفتاح', 'ما معنى رؤية المفتاح في الحلم؟', 'المفتاح يرمز للوصول والحلول وفتح الإمكانات.',
    'Soñar con llave', '¿Qué significa soñar con llave?', 'La llave representa acceso.',
    'Rêve de clé', 'Que signifie rêver de clé?', 'La clé représente l\'accès.',
    'Schlüssel im Traum', 'Was bedeutet Schlüssel im Traum?', 'Ein Schlüssel symbolisiert Zugang.',
    'Sonhar com chave', 'O que significa sonhar com chave?', 'A chave representa acesso.',
    'Сон о ключе', 'Что значит сон о ключе?', 'Ключ символизирует доступ.',
    '梦见钥匙的含义', '梦见钥匙是什么意思？', '钥匙代表开启与解答。',
    '鍵の夢', '鍵の夢は何を意味する？', '鍵は解決を表す。',
    '열쇠 꿈 해몽', '열쇠 꿈은 무슨 의미일까?', '열쇠는 접근과 해답을 나타냅니다.',
    'Anahtar rüyası', 'Anahtar görmek ne anlama gelir?', 'Anahtar erişimi simgeler.',
    'चाबी का सपना', 'सपने में चाबी क्या मतलब?', 'चाबी पहुँच व सुलझाव है।',
    'Sogno di chiave', 'Cosa significa sognare chiave?', 'La chiave rappresenta l\'accesso.',
  ],
  mirror: [
    'Mirror Dream Meaning', 'What Does It Mean to Dream About a Mirror?', 'A mirror represents self-reflection, truth, and how you see yourself.',
    'تفسير حلم المرآة', 'ما معنى رؤية المرآة في الحلم؟', 'المرآة ترمز للتأمل الذاتي والحقيقة.',
    'Soñar con espejo', '¿Qué significa soñar con espejo?', 'El espejo representa auto-reflexión.',
    'Rêve de miroir', 'Que signifie rêver de miroir?', 'Le miroir représente l\'introspection.',
    'Spiegel im Traum', 'Was bedeutet Spiegel im Traum?', 'Ein Spiegel symbolisiert Selbstreflexion.',
    'Sonhar com espelho', 'O que significa sonhar com espelho?', 'O espelho representa auto-reflexão.',
    'Сон о зеркале', 'Что значит сон о зеркале?', 'Зеркало символизирует самопознание.',
    '梦见镜子的含义', '梦见镜子是什么意思？', '镜子代表自省与真相。',
    '鏡の夢', '鏡の夢は何を意味する？', '鏡は自己 reflection を表す。',
    '거울 꿈 해몽', '거울 꿈은 무슨 의미일까?', '거울은 자기 성찰을 나타냅니다.',
    'Ayna rüyası', 'Ayna görmek ne anlama gelir?', 'Ayna kendini yansıtmayı simgeler.',
    'शीशे का सपना', 'सपने में शीशा क्या मतलब?', 'शीशा आत्म-चिंतन का प्रतीक है।',
    'Sogno di specchio', 'Cosa significa sognare specchio?', 'Lo specchio rappresenta l\'introspezione.',
  ],
  mother: [
    'Mother Dream Meaning', 'What Does It Mean to Dream About Your Mother?', 'A mother represents nurturing, protection, and your roots. She reflects your emotional foundation.',
    'تفسير حلم الأم', 'ما معنى رؤية الأم في الحلم؟', 'الأم ترمز للرعاية والحماية والجذور.',
    'Soñar con madre', '¿Qué significa soñar con tu madre?', 'La madre representa cuidado.',
    'Rêve de mère', 'Que signifie rêver de sa mère?', 'La mère représente la protection.',
    'Mutter im Traum', 'Was bedeutet Mutter im Traum?', 'Eine Mutter symbolisiert Fürsorge.',
    'Sonhar com mãe', 'O que significa sonhar com mãe?', 'A mãe representa cuidado.',
    'Сон о матери', 'Что значит сон о матери?', 'Мать символизирует заботу.',
    '梦见母亲的的含义', '梦见母亲是什么意思？', '母亲代表养育与根基。',
    '母の夢', '母の夢は何を意味する？', '母は養いを表す。',
    '어머니 꿈 해몽', '어머니 꿈은 무슨 의미일까?', '어머니는 보살핌을 나타냅니다.',
    'Anne rüyası', 'Anne görmek ne anlama gelir?', 'Anne şefkati simgeler.',
    'माँ का सपना', 'सपने में माँ क्या मतलब?', 'माँ देखभाल व संरक्षण है।',
    'Sogno di madre', 'Cosa significa sognare la madre?', 'La madre rappresenta la cura.',
  ],
  father: [
    'Father Dream Meaning', 'What Does It Mean to Dream About Your Father?', 'A father represents authority, guidance, and your sense of structure and discipline.',
    'تفسير حلم الأب', 'ما معنى رؤية الأب في الحلم؟', 'الأب يرمز للسلطة والإرشاد والانضباط.',
    'Soñar con padre', '¿Qué significa soñar con tu padre?', 'El padre representa autoridad.',
    'Rêve de père', 'Que signifie rêver de son père?', 'Le père représente l\'autorité.',
    'Vater im Traum', 'Was bedeutet Vater im Traum?', 'Ein Vater symbolisiert Autorität.',
    'Sonhar com pai', 'O que significa sonhar com pai?', 'O pai representa autoridade.',
    'Сон об отце', 'Что значит сон об отце?', 'Отец символизирует власть.',
    '梦见父亲的含义', '梦见父亲是什么意思？', '父亲代表权威与指引。',
    '父の夢', '父の夢は何を意味する？', '父は権威を表す。',
    '아버지 꿈 해몽', '아버지 꿈은 무슨 의미일까?', '아버지는 권위를 나타냅니다.',
    'Baba rüyası', 'Baba görmek ne anlama gelir?', 'Baba otoriteyi simgeler.',
    'पिता का सपना', 'सपने में पिता क्या मतलब?', 'पिता अधिकार व मार्गदर्शन है।',
    'Sogno di padre', 'Cosa significa sognare il padre?', 'Il padre rappresenta l\'autorità.',
  ],
  friend: [
    'Friend Dream Meaning', 'What Does It Mean to Dream About a Friend?', 'A friend represents support, your social self, and aspects of your personality.',
    'تفسير حلم الصديق', 'ما معنى رؤية الصديق في الحلم؟', 'الصديق يرمز للدعم والجانب الاجتماعي من شخصيتك.',
    'Soñar con amigo', '¿Qué significa soñar con un amigo?', 'El amigo representa apoyo.',
    'Rêve d\'ami', 'Que signifie rêver d\'ami?', 'L\'ami représente le soutien.',
    'Freund im Traum', 'Was bedeutet Freund im Traum?', 'Ein Freund symbolisiert Unterstützung.',
    'Sonhar com amigo', 'O que significa sonhar com amigo?', 'O amigo representa apoio.',
    'Сон о друге', 'Что значит сон о друге?', 'Друг символизирует поддержку.',
    '梦见朋友的含义', '梦见朋友是什么意思？', '朋友代表支持与自我社交。',
    '友達の夢', '友達の夢は何を意味する？', '友達は支援を表す。',
    '친구 꿈 해몽', '친구 꿈은 무슨 의미일까?', '친구는 지지를 나타냅니다.',
    'Arkadaş rüyası', 'Arkadaş görmek ne anlama gelir?', 'Arkadaş desteği simgeler.',
    'दोस्त का सपना', 'सपने में दोस्त क्या मतलब?', 'दोस्त समर्थन व सामाजिकता है।',
    'Sogno di amico', 'Cosa significa sognare un amico?', 'L\'amico rappresenta il sostegno.',
  ],
  running: [
    'Running Dream Meaning', 'What Does It Mean to Dream About Running?', 'Running represents escape, ambition, or avoiding something. Running freely suggests progress.',
    'تفسير حلم الركض', 'ما معنى رؤية الركض في الحلم؟', 'الركض يرمز للهروب والطموح أو التجنب.',
    'Soñar con correr', '¿Qué significa soñar con correr?', 'Correr representa escape.',
    'Rêve de course', 'Que signifie rêver de courir?', 'Courir représente l\'échappement.',
    'Rennen im Traum', 'Was bedeutet Rennen im Traum?', 'Rennen symbolisiert Flucht.',
    'Sonhar com correr', 'O que significa sonhar com correr?', 'Correr representa fuga.',
    'Сон о беге', 'Что значит сон о беге?', 'Бег символизирует побег.',
    '梦见跑步的含义', '梦见跑步是什么意思？', '跑步代表逃避与进取。',
    '走る夢', '走る夢は何を意味する？', '走ることは逃避を表す。',
    '달리기 꿈 해몽', '달리기 꿈은 무슨 의미일까?', '달리기는 도피를 나타냅니다.',
    'Koşmak rüyası', 'Koşmak görmek ne anlama gelir?', 'Koşmak kaçışı simgeler.',
    'दौड़ने का सपना', 'सपने में दौड़ना क्या मतलब?', 'दौड़ना बचाव व महत्वाकांक्षा है।',
    'Sogno di correre', 'Cosa significa sognare di correre?', 'Correre rappresenta la fuga.',
  ],
  fighting: [
    'Fighting Dream Meaning', 'What Does It Mean to Dream About Fighting?', 'Fighting represents inner conflict, suppressed anger, or a struggle for control.',
    'تفسير حلم القتال', 'ما معنى رؤية القتال في الحلم؟', 'القتال يرمز للصراع الداخلي والغضب المكبوت.',
    'Soñar con pelear', '¿Qué significa soñar con pelear?', 'Pelear representa conflicto.',
    'Rêve de combat', 'Que signifie rêver de combat?', 'Le combat représente le conflit.',
    'Kampf im Traum', 'Was bedeutet Kampf im Traum?', 'Ein Kampf symbolisiert Konflikt.',
    'Sonhar com lutar', 'O que significa sonhar com lutar?', 'Lutar representa conflito.',
    'Сон о драке', 'Что значит сон о драке?', 'Драка символизирует конфликт.',
    '梦见打架的含义', '梦见打架是什么意思？', '打架代表内心冲突。',
    '戦う夢', '戦う夢は何を意味する？', '戦うことは内面の葛藤を表す。',
    '싸움 꿈 해몽', '싸움 꿈은 무슨 의미일까?', '싸움은 내면의 갈등을 나타냅니다.',
    'Kavga rüyası', 'Kavga görmek ne anlama gelir?', 'Kavga içsel çatışmayı simgeler.',
    'लड़ाई का सपना', 'सपने में लड़ाई क्या मतलब?', 'लड़ाई आंतरिक संघर्ष है।',
    'Sogno di combattere', 'Cosa significa sognare di combattere?', 'Combattere rappresenta il conflitto.',
  ],
  hospital: [
    'Hospital Dream Meaning', 'What Does It Mean to Dream About a Hospital?', 'A hospital represents healing, vulnerability, and a need for care or recovery.',
    'تفسير حلم المستشفى', 'ما معنى رؤية المستشفى في الحلم؟', 'المستشفى يرمز للشفاء والضعف والحاجة للرعاية.',
    'Soñar con hospital', '¿Qué significa soñar con hospital?', 'El hospital representa sanación.',
    'Rêve d\'hôpital', 'Que signifie rêver d\'hôpital?', 'L\'hôpital représente la guérison.',
    'Krankenhaus im Traum', 'Was bedeutet Krankenhaus im Traum?', 'Ein Krankenhaus symbolisiert Heilung.',
    'Sonhar com hospital', 'O que significa sonhar com hospital?', 'O hospital representa cura.',
    'Сон о больнице', 'Что значит сон о больнице?', 'Больница символизирует исцеление.',
    '梦见医院的含义', '梦见医院是什么意思？', '医院代表治愈与脆弱。',
    '病院の夢', '病院の夢は何を意味する？', '病院は癒やしを表す。',
    '병원 꿈 해몽', '병원 꿈은 무슨 의미일까?', '병원은 치유를 나타냅니다.',
    'Hastane rüyası', 'Hastane görmek ne anlama gelir?', 'Hastane şifayı simgeler.',
    'अस्पताल का सपना', 'सपने में अस्पताल क्या मतलब?', 'अस्पताल चिकित्सा व स्वास्थ्य है।',
    'Sogno di ospedale', 'Cosa significa sognare ospedale?', 'L\'ospedale rappresenta la guarigione.',
  ],
};
