// 13 languages order: en, ar, es, fr, de, pt, ru, zh, ja, ko, tr, hi, it
// Each symbol: [en_t,en_h,en_m, ar_t,ar_h,ar_m, es..., it (13x3 = 39 strings)]
// NEW symbols not present in core SYM / batch2 / batch3 / batch4.
export const BATCH5_SYMBOLS = {
  finger: [
    'Finger Dream Meaning', 'What Does It Mean to Dream About Fingers?', 'Fingers symbolize skill, detail, and the way you handle the small things in life.',
    'تفسير حلم الأصبع', 'ما معنى رؤية الأصبع في الحلم؟', 'الأصبع يرمز للمهارة والتفاصيل وطريقة تعاملك مع الأمور الصغيرة.',
    'Soñar con dedos', '¿Qué significa soñar con dedos?', 'Los dedos simbolizan habilidad y detalle.',
    'Rêve de doigts', 'Que signifie rêver de doigts?', 'Les doigts symbolisent adresse et détail.',
    'Finger im Traum', 'Was bedeutet Finger im Traum?', 'Finger symbolisieren Geschick und Detail.',
    'Sonhar com dedos', 'O que significa sonhar com dedos?', 'Os dedos representam habilidade e detalhe.',
    'Сон о пальцах', 'Что значит сон о пальцах?', 'Пальцы символизируют умение и детали.',
    '梦见手指的含义', '梦见手指是什么意思？', '手指象征技巧与细节。',
    '指の夢', '指の夢は何を意味する？', '指は技巧と細部を表す。',
    '손가락 꿈', '손가락 꿈은 무슨 의미일까?', '손가락은 기술과 세부를 나타냅니다.',
    'Parmak rüyası', 'Parmak görmek ne anlama gelir?', 'Parmaklar beceriyi ve detayı simgeler.',
    'उंगली का सपना', 'सपने में उंगली क्या मतलब?', 'उंगलियाँ कौशल और बारीकी का प्रतीक हैं।',
    'Sogno di dita', 'Cosa significa sognare le dita?', 'Le dita rappresentano abilità e dettaglio.',
  ],
  ear: [
    'Ear Dream Meaning', 'What Does It Mean to Dream About Ears?', 'Ears symbolize listening, receiving messages, and how open you are to truth.',
    'تفسير حلم الأذن', 'ما معنى رؤية الأذن في الحلم؟', 'الأذن ترمز للاستماع واستقبال الرسائل ومدى انفتاحك على الحقيقة.',
    'Soñar con orejas', '¿Qué significa soñar con orejas?', 'Las orejas simbolizan escuchar y recibir.',
    'Rêve d’oreilles', 'Que signifie rêver d’oreilles?', 'Les oreilles symbolisent écoute et réception.',
    'Ohr im Traum', 'Was bedeutet Ohr im Traum?', 'Ein Ohr symbolisiert Zuhören und Empfang.',
    'Sonhar com orelhas', 'O que significa sonhar com orelhas?', 'As orelhas representam ouvir e receber.',
    'Сон об ушах', 'Что значит сон об ушах?', 'Уши символизируют слушание и приём.',
    '梦见耳朵的含义', '梦见耳朵是什么意思？', '耳朵象征倾听与接收。',
    '耳の夢', '耳の夢は何を意味する？', '耳は聞くことと受け取ることを表す。',
    '귀 꿈', '귀 꿈은 무슨 의미일까?', '귀는 듣기와 받아들이기를 나타냅니다.',
    'Kulak rüyası', 'Kulak görmek ne anlama gelir?', 'Kulak dinlemeyi ve almayı simgeler.',
    'कान का सपना', 'सपने में कान क्या मतलब?', 'कान सुनने और स्वीकार का प्रतीक है।',
    'Sogno di orecchie', 'Cosa significa sognare le orecchie?', 'Le orecchie rappresentano ascolto e ricezione.',
  ],
  tongue: [
    'Tongue Dream Meaning', 'What Does It Mean to Dream About a Tongue?', 'A tongue symbolizes expression, taste for life, and words that heal or hurt.',
    'تفسير حلم اللسان', 'ما معنى رؤية اللسان في الحلم؟', 'اللسان يرمز للتعبير ولذة الحياة والكلمات اللي تشفي أو تجرح.',
    'Soñar con lengua', '¿Qué significa soñar con lengua?', 'La lengua simboliza expresión y palabra.',
    'Rêve de langue', 'Que signifie rêver de langue?', 'La langue symbolise expression et parole.',
    'Zunge im Traum', 'Was bedeutet Zunge im Traum?', 'Eine Zunge symbolisiert Ausdruck und Wort.',
    'Sonhar com língua', 'O que significa sonhar com língua?', 'A língua representa expressão e palavra.',
    'Сон о языке', 'Что значит сон о языке?', 'Язык символизирует выражение и слово.',
    '梦见舌头的含义', '梦见舌头是什么意思？', '舌头象征表达与言语。',
    '舌の夢', '舌の夢は何を意味する？', '舌は表現と言葉を表す。',
    '혀 꿈', '혀 꿈은 무슨 의미일까?', '혀는 표현과 말을 나타냅니다.',
    'Dil rüyası', 'Dil görmek ne anlama gelir?', 'Dil ifadeyi ve sözü simgeler.',
    'जीभ का सपना', 'सपने में जीभ क्या मतलब?', 'जीभ अभिव्यक्ति और वाणी का प्रतीक है।',
    'Sogno di lingua', 'Cosa significa sognare la lingua?', 'La lingua rappresenta espressione e parola.',
  ],
  knee: [
    'Knee Dream Meaning', 'What Does It Mean to Dream About Knees?', 'Knees symbolize humility, flexibility, and where you bend under pressure.',
    'تفسير حلم الركبة', 'ما معنى رؤية الركبة في الحلم؟', 'الركبة ترمز للتواضع والمرونة والمكان اللي بتنثني فيه تحت الضغط.',
    'Soñar con rodillas', '¿Qué significa soñar con rodillas?', 'Las rodillas simbolizan humildad y flexibilidad.',
    'Rêve de genoux', 'Que signifie rêver de genoux?', 'Les genoux symbolisent humilité et souplesse.',
    'Knie im Traum', 'Was bedeutet Knie im Traum?', 'Knie symbolisiert Demut und Flexibilität.',
    'Sonhar com joelhos', 'O que significa sonhar com joelhos?', 'Os joelhos representam humildade e flexibilidade.',
    'Сон о коленях', 'Что значит сон о коленях?', 'Колени символизируют смирение и гибкость.',
    '梦见膝盖的含义', '梦见膝盖是什么意思？', '膝盖象征谦卑与柔韧。',
    '膝の夢', '膝の夢は何を意味する？', '膝は謙虚と柔軟性を表す。',
    '무릎 꿈', '무릎 꿈은 무슨 의미일까?', '무릎은 겸손과 유연성을 나타냅니다.',
    'Diz rüyası', 'Diz görmek ne anlama gelir?', 'Dizler alçakgönüllülüğü ve esnekliği simgeler.',
    'घुटने का सपना', 'सपने में घुटने क्या मतलब?', 'घुटने विनम्रता और लचीलेपन का प्रतीक हैं।',
    'Sogno di ginocchia', 'Cosa significa sognare le ginocchia?', 'Le ginocchia rappresentano umiltà e flessibilità.',
  ],
  elbow: [
    'Elbow Dream Meaning', 'What Does It Mean to Dream About an Elbow?', 'An elbow symbolizes adaptation, the turns you make, and personal boundaries.',
    'تفسير حلم المرفق', 'ما معنى رؤية المرفق في الحلم؟', 'المرفق يرمز للتكيف والمنعطفات اللي بتعملها ولحدودك الشخصية.',
    'Soñar con codo', '¿Qué significa soñar con codo?', 'El codo simboliza adaptación y límites.',
    'Rêve de coude', 'Que signifie rêver de coude?', 'Le coude symbolise adaptation et limites.',
    'Ellbogen im Traum', 'Was bedeutet Ellbogen im Traum?', 'Ein Ellbogen symbolisiert Anpassung und Grenzen.',
    'Sonhar com cotovelo', 'O que significa sonhar com cotovelo?', 'O cotovelo representa adaptação e limites.',
    'Сон о локте', 'Что значит сон о локте?', 'Локоть символизирует адаптацию и границы.',
    '梦见肘部的含义', '梦见肘部是什么意思？', '肘部象征适应与界限。',
    '肘の夢', '肘の夢は何を意味する？', '肘は適応と境界を表す。',
    '팔꿈치 꿈', '팔꿈치 꿈은 무슨 의미일까?', '팔꿈치는 적응과 경계를 나타냅니다.',
    'Dirsek rüyası', 'Dirsek görmek ne anlama gelir?', 'Dirsek uyumu ve sınırları simgeler.',
    'कोहनी का सपना', 'सपने में कोहनी क्या मतलब?', 'कोहनी अनुकूलन और सीमाओं का प्रतीक है।',
    'Sogno di gomito', 'Cosa significa sognare il gomito?', 'Il gomito rappresenta adattamento e confini.',
  ],
  shoulder: [
    'Shoulder Dream Meaning', 'What Does It Mean to Dream About Shoulders?', 'Shoulders symbolize responsibility, burden, and the weight you carry.',
    'تفسير حلم الكتف', 'ما معنى رؤية الكتف في الحلم؟', 'الكتف يرمز للمسؤولية والعبء والوزن اللي بتشيله.',
    'Soñar con hombros', '¿Qué significa soñar con hombros?', 'Los hombros simbolizan responsabilidad y carga.',
    'Rêve d’épaules', 'Que signifie rêver d’épaules?', 'Les épaules symbolisent responsabilité et fardeau.',
    'Schulter im Traum', 'Was bedeutet Schulter im Traum?', 'Schultern symbolisieren Verantwortung und Last.',
    'Sonhar com ombros', 'O que significa sonhar com ombros?', 'Os ombros representam responsabilidade e peso.',
    'Сон о плечах', 'Что значит сон о плечах?', 'Плечи символизируют ответственность и ношу.',
    '梦见肩膀的含义', '梦见肩膀是什么意思？', '肩膀象征责任与重担。',
    '肩の夢', '肩の夢は何を意味する？', '肩は責任と重荷を表す。',
    '어깨 꿈', '어깨 꿈은 무슨 의미일까?', '어깨는 책임과 짐을 나타냅니다.',
    'Omuz rüyası', 'Omuz görmek ne anlama gelir?', 'Omuzlar sorumluluğu ve yükü simgeler.',
    'कंधे का सपना', 'सपने में कंधे क्या मतलब?', 'कंधे ज़िम्मेदारी और बोझ का प्रतीक हैं।',
    'Sogno di spalle', 'Cosa significa sognare le spalle?', 'Le spalle rappresentano responsabilità e carico.',
  ],
  neck: [
    'Neck Dream Meaning', 'What Does It Mean to Dream About a Neck?', 'A neck symbolizes connection, vulnerability, and the bridge between thought and action.',
    'تفسير حلم الرقبة', 'ما معنى رؤية الرقبة في الحلم؟', 'الرقبة ترمز للاتصال والهشاشة والجسر بين التفكير والفعل.',
    'Soñar con cuello', '¿Qué significa soñar con cuello?', 'El cuello simboliza conexión y vulnerabilidad.',
    'Rêve de cou', 'Que signifie rêver de cou?', 'Le cou symbolise lien et vulnérabilité.',
    'Hals im Traum', 'Was bedeutet Hals im Traum?', 'Ein Hals symbolisiert Verbindung und Verletzlichkeit.',
    'Sonhar com pescoço', 'O que significa sonhar com pescoço?', 'O pescoço representa conexão e vulnerabilidade.',
    'Сон о шее', 'Что значит сон о шее?', 'Шея символизирует связь и уязвимость.',
    '梦见脖子的含义', '梦见脖子是什么意思？', '脖子象征连接与脆弱。',
    '首の夢', '首の夢は何を意味する？', '首は繋がりと脆弱さを表す。',
    '목 꿈', '목 꿈은 무슨 의미일까?', '목은 연결과 취약성을 나타냅니다.',
    'Boyun rüyası', 'Boyun görmek ne anlama gelir?', 'Boyun bağı ve kırılganlığı simgeler.',
    'गले का सपना', 'सपने में गला क्या मतलब?', 'गला जुड़ाव और घायलपन का प्रतीक है।',
    'Sogno di collo', 'Cosa significa sognare il collo?', 'Il collo rappresenta connessione e vulnerabilità.',
  ],
  back: [
    'Back Dream Meaning', 'What Does It Mean to Dream About a Back?', 'A back symbolizes support, the past, and what you turn away from.',
    'تفسير حلم الظهر', 'ما معنى رؤية الظهر في الحلم؟', 'الظهر يرمز للدعم والماضي ولي بتوليه ظهرك.',
    'Soñar con espalda', '¿Qué significa soñar con espalda?', 'La espalda simboliza apoyo y pasado.',
    'Rêve de dos', 'Que signifie rêver de dos?', 'Le dos symbolise soutien et passé.',
    'Rücken im Traum', 'Was bedeutet Rücken im Traum?', 'Ein Rücken symbolisiert Halt und Vergangenheit.',
    'Sonhar com costas', 'O que significa sonhar com costas?', 'As costas representam apoio e passado.',
    'Сон о спине', 'Что значит сон о спине?', 'Спина символизирует поддержку и прошлое.',
    '梦见后背的含义', '梦见后背是什么意思？', '后背象征支持与过去。',
    '背中の夢', '背中の夢は何を意味する？', '背中は支えと過去を表す。',
    '등 꿈', '등 꿈은 무슨 의미일까?', '등은 지지와 과거를 나타냅니다.',
    'Sırt rüyası', 'Sırt görmek ne anlama gelir?', 'Sırt desteği ve geçmişi simgeler.',
    'पीठ का सपना', 'सपने में पीठ क्या मतलब?', 'पीठ समर्थन और अतीत का प्रतीक है।',
    'Sogno di schiena', 'Cosa significa sognare la schiena?', 'La schiena rappresenta sostegno e passato.',
  ],
  belly: [
    'Belly Dream Meaning', 'What Does It Mean to Dream About a Belly?', 'A belly symbolizes intuition, gut feeling, and hidden emotion.',
    'تفسير حلم البطن', 'ما معنى رؤية البطن في الحلم؟', 'البطن يرمز للحدس والإحساس الداخلي والعاطفة المخفية.',
    'Soñar con barriga', '¿Qué significa soñar con barriga?', 'La barriga simboliza intuición y emoción.',
    'Rêve de ventre', 'Que signifie rêver de ventre?', 'Le ventre symbolise intuition et émotion.',
    'Bauch im Traum', 'Was bedeutet Bauch im Traum?', 'Ein Bauch symbolisiert Intuition und Gefühl.',
    'Sonhar com barriga', 'O que significa sonhar com barriga?', 'A barriga representa intuição e emoção.',
    'Сон о животе', 'Что значит сон о животе?', 'Живот символизирует интуицию и чувство.',
    '梦见肚子的含义', '梦见肚子是什么意思？', '肚子象征直觉与情感。',
    '腹の夢', '腹の夢は何を意味する？', '腹は直感と感情を表す。',
    '배 꿈', '배 꿈은 무슨 의미일까?', '배는 직관과 감정을 나타냅니다.',
    'Göbek rüyası', 'Göbek görmek ne anlama gelir?', 'Göbek sezgiyi ve duyguyu simgeler.',
    'पेट का सपना', 'सपने में पेट क्या मतलब?', 'पेट अंतर्ज्ञान और भावना का प्रतीक है।',
    'Sogno di pancia', 'Cosa significa sognare la pancia?', 'La pancia rappresenta intuizione ed emozione.',
  ],
  chest: [
    'Chest Dream Meaning', 'What Does It Mean to Dream About a Chest?', 'A chest symbolizes what you protect, your heart center, and hidden treasure.',
    'تفسير حلم الصدر', 'ما معنى رؤية الصدر في الحلم؟', 'الصدر يرمز للي بتحميه ولمركز قلبك والكنز المخفي.',
    'Soñar con pecho', '¿Qué significa soñar con pecho?', 'El pecho simboliza lo que proteges y tu centro.',
    'Rêve de poitrine', 'Que signifie rêver de poitrine?', 'La poitrine symbolise ce que vous protégez.',
    'Brust im Traum', 'Was bedeutet Brust im Traum?', 'Eine Brust symbolisiert das, was du schützt.',
    'Sonhar com peito', 'O que significa sonhar com peito?', 'O peito representa o que você protege.',
    'Сон о груди', 'Что значит сон о груди?', 'Грудь символизирует то, что вы защищаете.',
    '梦见胸部的含义', '梦见胸部是什么意思？', '胸部象征你守护之物。',
    '胸の夢', '胸の夢は何を意味する？', '胸は守るものと心の中心を表す。',
    '가슴 꿈', '가슴 꿈은 무슨 의미일까?', '가슴은 지키는 것과 마음의 중심을 나타냅니다.',
    'Göğüs rüyası', 'Göğüs görmek ne anlama gelir?', 'Göğüs koruduklarını ve merkezi simgeler.',
    'छाती का सपना', 'सपने में छाती क्या मतलब?', 'छाती आपकी रक्षा और हृदय केंद्र का प्रतीक है।',
    'Sogno di petto', 'Cosa significa sognare il petto?', 'Il petto rappresenta ciò che proteggi.',
  ],
  skin: [
    'Skin Dream Meaning', 'What Does It Mean to Dream About Skin?', 'Skin symbolizes identity, sensitivity, and how you meet the world.',
    'تفسير حلم الجلد', 'ما معنى رؤية الجلد في الحلم؟', 'الجلد يرمز لهويتك وحساسيتك وطريقة لقائك بالعالم.',
    'Soñar con piel', '¿Qué significa soñar con piel?', 'La piel simboliza identidad y sensibilidad.',
    'Rêve de peau', 'Que signifie rêver de peau?', 'La peau symbolise identité et sensibilité.',
    'Haut im Traum', 'Was bedeutet Haut im Traum?', 'Haut symbolisiert Identität und Sensibilität.',
    'Sonhar com pele', 'O que significa sonhar com pele?', 'A pele representa identidade e sensibilidade.',
    'Сон о коже', 'Что значит сон о коже?', 'Кожа символизирует личность и чувствительность.',
    '梦见皮肤的含义', '梦见皮肤是什么意思？', '皮肤象征身份与敏感。',
    '肌の夢', '肌の夢は何を意味する？', '肌はアイデンティティと感受性を表す。',
    '피부 꿈', '피부 꿈은 무슨 의미일까?', '피부는 정체성과 민감성을 나타냅니다.',
    'Cilt rüyası', 'Cilt görmek ne anlama gelir?', 'Cilt kimliği ve duyarlılığı simgeler.',
    'त्वचा का सपना', 'सपने में त्वचा क्या मतलब?', 'त्वचा पहचान और संवेदनशीलता का प्रतीक है।',
    'Sogno di pelle', 'Cosa significa sognare la pelle?', 'La pelle rappresenta identità e sensibilità.',
  ],
  bone: [
    'Bone Dream Meaning', 'What Does It Mean to Dream About Bones?', 'Bones symbolize structure, deepest truth, and what remains when surfaces fade.',
    'تفسير حلم العظم', 'ما معنى رؤية العظم في الحلم؟', 'العظم يرمز للبنية وأعمق حقيقة وما يبقى لما تختفي السطور.',
    'Soñar con huesos', '¿Qué significa soñar con huesos?', 'Los huesos simbolizan estructura y verdad profunda.',
    'Rêve d’os', 'Que signifie rêver d’os?', 'Les os symbolisent structure et vérité profonde.',
    'Knochen im Traum', 'Was bedeutet Knochen im Traum?', 'Knochen symbolisieren Struktur und tiefe Wahrheit.',
    'Sonhar com ossos', 'O que significa sonhar com ossos?', 'Os ossos representam estrutura e verdade profunda.',
    'Сон о костях', 'Что значит сон о костях?', 'Кости символизируют структуру и глубокую правду.',
    '梦见骨头的含义', '梦见骨头是什么意思？', '骨头象征结构与深层真相。',
    '骨の夢', '骨の夢は何を意味する？', '骨は構造と深い真実を表す。',
    '뼈 꿈', '뼈 꿈은 무슨 의미일까?', '뼈는 구조와 깊은 진실을 나타냅니다.',
    'Kemik rüyası', 'Kemik görmek ne anlama gelir?', 'Kemikler yapıyı ve derin gerçeği simgeler.',
    'हड्डी का सपना', 'सपने में हड्डी क्या मतलब?', 'हड्डियाँ संरचना और गहरी सच्चाई का प्रतीक हैं।',
    'Sogno di ossa', 'Cosa significa sognare le ossa?', 'Le ossa rappresentano struttura e verità profonda.',
  ],
  surgery: [
    'Surgery Dream Meaning', 'What Does It Mean to Dream About Surgery?', 'Surgery symbolizes necessary change, healing, and removing what no longer serves you.',
    'تفسير حلم الجراحة', 'ما معنى رؤية الجراحة في الحلم؟', 'الجراحة ترمز للتغيير الضروري والشفاء وإزالة اللي مابقاش يخدمك.',
    'Soñar con cirugía', '¿Qué significa soñar con cirugía?', 'La cirugía simboliza cambio necesario y sanación.',
    'Rêve de chirurgie', 'Que signifie rêver de chirurgie?', 'La chirurgie symbolise changement nécessaire et guérison.',
    'Operation im Traum', 'Was bedeutet Operation im Traum?', 'Eine Operation symbolisiert nötige Veränderung und Heilung.',
    'Sonhar com cirurgia', 'O que significa sonhar com cirurgia?', 'A cirurgia representa mudança necessária e cura.',
    'Сон об операции', 'Что значит сон об операции?', 'Операция символизирует нужное изменение и исцеление.',
    '梦见手术的含义', '梦见手术是什么意思？', '手术象征必要的改变与治愈。',
    '手術の夢', '手術の夢は何を意味する？', '手術は必要な変化と癒やしを表す。',
    '수술 꿈', '수술 꿈은 무슨 의미일까?', '수술은 필요한 변화와 치유를 나타냅니다.',
    'Ameliyat rüyası', 'Ameliyat görmek ne anlama gelir?', 'Ameliyat gerekli değişimi ve şifayı simgeler.',
    'सर्जरी का सपना', 'सपने में सर्जरी क्या मतलब?', 'सर्जरी आवश्यक परिवर्तन और चिकित्सा का प्रतीक है।',
    'Sogno di chirurgia', 'Cosa significa sognare la chirurgia?', 'La chirurgia rappresenta cambiamento necessario e guarigione.',
  ],
  medicine: [
    'Medicine Dream Meaning', 'What Does It Mean to Dream About Medicine?', 'Medicine symbolizes healing, relief, and the remedy your life is asking for.',
    'تفسير حلم الدواء', 'ما معنى رؤية الدواء في الحلم؟', 'الدواء يرمز للشفاء والراحة والعلاج اللي حياتك محتاجاه.',
    'Soñar con medicina', '¿Qué significa soñar con medicina?', 'La medicina simboliza sanación y alivio.',
    'Rêve de médicament', 'Que signifie rêver de médicament?', 'Le médicament symbolise guérison et soulagement.',
    'Medizin im Traum', 'Was bedeutet Medizin im Traum?', 'Medizin symbolisiert Heilung und Linderung.',
    'Sonhar com remédio', 'O que significa sonhar com remédio?', 'O remédio representa cura e alívio.',
    'Сон о лекарстве', 'Что значит сон о лекарстве?', 'Лекарство символизирует исцеление и облегчение.',
    '梦见药的含义', '梦见药是什么意思？', '药象征治愈与缓解。',
    '薬の夢', '薬の夢は何を意味する？', '薬は癒やしと軽減を表す。',
    '약 꿈', '약 꿈은 무슨 의미일까?', '약은 치유와 안도를 나타냅니다.',
    'İlaç rüyası', 'İlaç görmek ne anlama gelir?', 'İlaç şifayı ve rahatlamayı simgeler.',
    'दवा का सपना', 'सपने में दवा क्या मतलब?', 'दवा चिकित्सा और राहत का प्रतीक है।',
    'Sogno di medicina', 'Cosa significa sognare la medicina?', 'La medicina rappresenta guarigione e sollievo.',
  ],
  doctor: [
    'Doctor Dream Meaning', 'What Does It Mean to Dream About a Doctor?', 'A doctor symbolizes authority, healing, and the part of you that knows what to fix.',
    'تفسير حلم الطبيب', 'ما معنى رؤية الطبيب في الحلم؟', 'الطبيب يرمز للسلطة والشفاء والجزء منك اللي بيعرف إيه اللي محتاج إصلاح.',
    'Soñar con médico', '¿Qué significa soñar con médico?', 'El médico simboliza autoridad y sanación.',
    'Rêve de médecin', 'Que signifie rêver de médecin?', 'Le médecin symbolise autorité et guérison.',
    'Arzt im Traum', 'Was bedeutet Arzt im Traum?', 'Ein Arzt symbolisiert Autorität und Heilung.',
    'Sonhar com médico', 'O que significa sonhar com médico?', 'O médico representa autoridade e cura.',
    'Сон о враче', 'Что значит сон о враче?', 'Врач символизирует власть и исцеление.',
    '梦见医生的含义', '梦见医生是什么意思？', '医生象征权威与治愈。',
    '医者の夢', '医者の夢は何を意味する？', '医者は権威と癒やしを表す。',
    '의사 꿈', '의사 꿈은 무슨 의미일까?', '의사는 권위와 치유를 나타냅니다.',
    'Doktor rüyası', 'Doktor görmek ne anlama gelir?', 'Doktor otoriteyi ve şifayı simgeler.',
    'डॉक्टर का सपना', 'सपने में डॉक्टर क्या मतलब?', 'डॉक्टर अधिकार और चिकित्सा का प्रतीक है।',
    'Sogno di medico', 'Cosa significa sognare il medico?', 'Il medico rappresenta autorità e guarigione.',
  ],
  nurse: [
    'Nurse Dream Meaning', 'What Does It Mean to Dream About a Nurse?', 'A nurse symbolizes care, nurturing, and quiet support through difficulty.',
    'تفسير حلم الممرضة', 'ما معنى رؤية الممرضة في الحلم؟', 'الممرضة ترمز للرعاية والاحتضان والدعم الهادئ وقت الصعوبة.',
    'Soñar con enfermera', '¿Qué significa soñar con enfermera?', 'La enfermera simboliza cuidado y apoyo.',
    'Rêve d’infirmière', 'Que signifie rêver d’infirmière?', 'L’infirmière symbolise soin et soutien.',
    'Krankenschwester im Traum', 'Was bedeutet Krankenschwester im Traum?', 'Eine Krankenschwester symbolisiert Fürsorge und Halt.',
    'Sonhar com enfermeira', 'O que significa sonhar com enfermeira?', 'A enfermeira representa cuidado e apoio.',
    'Сон о медсестре', 'Что значит сон о медсестре?', 'Медсестра символизирует заботу и поддержку.',
    '梦见护士的含义', '梦见护士是什么意思？', '护士象征关怀与支持。',
    '看護師の夢', '看護師の夢は何を意味する？', '看護師はケアと支えを表す。',
    '간호사 꿈', '간호사 꿈은 무슨 의미일까?', '간호사는 돌봄과 지지를 나타냅니다.',
    'Hemşire rüyası', 'Hemşire görmek ne anlama gelir?', 'Hemşire bakımı ve desteği simgeler.',
    'नर्स का सपना', 'सपने में नर्स क्या मतलब?', 'नर्स देखभाल और सहारे का प्रतीक है।',
    'Sogno di infermiera', 'Cosa significa sognare l’infermiera?', 'L’infermiera rappresenta cura e sostegno.',
  ],
  injection: [
    'Injection Dream Meaning', 'What Does It Mean to Dream About an Injection?', 'An injection symbolizes a forced change, a quick fix, or fear handed to you.',
    'تفسير حلم الحقنة', 'ما معنى رؤية الحقنة في الحلم؟', 'الحقنة ترمز لتغيير قسري أو إصلاح سريع أو خوف بيوصلك.',
    'Soñar con inyección', '¿Qué significa soñar con inyección?', 'La inyección simboliza cambio forzado o arreglo rápido.',
    'Rêve d’injection', 'Que signifie rêver d’injection?', 'L’injection symbolise changement forcé ou solution rapide.',
    'Spritze im Traum', 'Was bedeutet Spritze im Traum?', 'Eine Spritze symbolisiert erzwungene Veränderung oder schnelle Lösung.',
    'Sonhar com injeção', 'O que significa sonhar com injeção?', 'A injeção representa mudança forçada ou solução rápida.',
    'Сон об уколе', 'Что значит сон об уколе?', 'Укол символизирует forced перемену или быстрое решение.',
    '梦见注射的含义', '梦见注射是什么意思？', '注射象征被迫改变或快速解决。',
    '注射の夢', '注射の夢は何を意味する？', '注射は強制な変化や迅速な解決を表す。',
    '주사 꿈', '주사 꿈은 무슨 의미일까?', '주사는 강제된 변화나 빠른 해결을 나타냅니다.',
    'İğne rüyası', 'İğne görmek ne anlama gelir?', 'İğne zorunlu değişimi veya hızlı çözümü simgeler.',
    'इंजेक्शन का सपना', 'सपने में इंजेक्शन क्या मतलब?', 'इंजेक्शन ज़बरदस्ती बदलाव या त्वरित समाधान का प्रतीक है।',
    'Sogno di iniezione', 'Cosa significa sognare l’iniezione?', 'L’iniezione rappresenta cambiamento forzato o soluzione rapida.',
  ],
  wound: [
    'Wound Dream Meaning', 'What Does It Mean to Dream About a Wound?', 'A wound symbolizes pain remembered, hurt not yet healed, and the need to tend yourself.',
    'تفسير حلم الجرح', 'ما معنى رؤية الجرح في الحلم؟', 'الجرح يرمز لألم لسه فاكرك إياه وجرح لسه ما اتشفاش وحاجتك ترعى نفسك.',
    'Soñar con herida', '¿Qué significa soñar con herida?', 'La herida simboliza dolor no curado y necesidad de cuidado.',
    'Rêve de blessure', 'Que signifie rêver de blessure?', 'La blessure symbolise douleur non guérie et soin.',
    'Wunde im Traum', 'Was bedeutet Wunde im Traum?', 'Eine Wunde symbolisiert ungeheilten Schmerz und Fürsorge.',
    'Sonhar com ferida', 'O que significa sonhar com ferida?', 'A ferida representa dor não curada e cuidado.',
    'Сон о ране', 'Что значит сон о ране?', 'Рана символизирует незажившую боль и заботу.',
    '梦见伤口的含义', '梦见伤口是什么意思？', '伤口象征未愈的痛与自我疗愈。',
    '傷の夢', '傷の夢は何を意味する？', '傷は癒えぬ痛みと自身のケアを表す。',
    '상처 꿈', '상처 꿈은 무슨 의미일까?', '상처는 낫지 않은 고통과 자기 돌봄을 나타냅니다.',
    'Yara rüyası', 'Yara görmek ne anlama gelir?', 'Yara iyileşmemiş acıyı ve özeni simgeler.',
    'घाव का सपना', 'सपने में घाव क्या मतलब?', 'घाव असुरक्षित दर्द और देखभाल का प्रतीक है।',
    'Sogno di ferita', 'Cosa significa sognare la ferita?', 'La ferita rappresenta dolore non guarito e cura.',
  ],
  scar: [
    'Scar Dream Meaning', 'What Does It Mean to Dream About a Scar?', 'A scar symbolizes survival, a story of healing, and lessons that stayed with you.',
    'تفسير حلم الندبة', 'ما معنى رؤية الندبة في الحلم؟', 'الندبة ترمز للنجاة وقصة شفاء ودروس فضلت معاك.',
    'Soñar con cicatriz', '¿Qué significa soñar con cicatriz?', 'La cicatriz simboliza supervivencia y sanación.',
    'Rêve de cicatrice', 'Que signifie rêver de cicatrice?', 'La cicatrice symbolise survie et guérison.',
    'Narbe im Traum', 'Was bedeutet Narbe im Traum?', 'Eine Narbe symbolisiert Überleben und Heilung.',
    'Sonhar com cicatriz', 'O que significa sonhar com cicatriz?', 'A cicatriz representa sobrevivência e cura.',
    'Сон о шраме', 'Что значит сон о шраме?', 'Шрам символизирует выживание и исцеление.',
    '梦见疤痕的含义', '梦见疤痕是什么意思？', '疤痕象征幸存与治愈。',
    '傷跡の夢', '傷跡の夢は何を意味する？', '傷跡は生存と癒やしを表す。',
    '흉터 꿈', '흉터 꿈은 무슨 의미일까?', '흉터는 생존과 치유를 나타냅니다.',
    'Yara izi rüyası', 'Yara izi görmek ne anlama gelir?', 'Yara izi hayatta kalmayı ve şifayı simgeler.',
    'दाग का सपना', 'सपने में दाग क्या मतलब?', 'दाग बचाव और चिकित्सा का प्रतीक है।',
    'Sogno di cicatrice', 'Cosa significa sognare la cicatrice?', 'La cicatrice rappresenta sopravvivenza e guarigione.',
  ],
  poison: [
    'Poison Dream Meaning', 'What Does It Mean to Dream About Poison?', 'Poison symbolizes toxicity, betrayal, and something harmful you have taken in.',
    'تفسير حلم السم', 'ما معنى رؤية السم في الحلم؟', 'السم يرمز للسموم والخيانة ولشيء ضار دخل جوهتك.',
    'Soñar con veneno', '¿Qué significa soñar con veneno?', 'El veneno simboliza toxicidad y traición.',
    'Rêve de poison', 'Que signifie rêver de poison?', 'Le poison symbolise toxicité et trahison.',
    'Gift im Traum', 'Was bedeutet Gift im Traum?', 'Gift symbolisiert Toxizität und Verrat.',
    'Sonhar com veneno', 'O que significa sonhar com veneno?', 'O veneno representa toxicidade e traição.',
    'Сон о яде', 'Что значит сон о яде?', 'Яд символизирует токсичность и предательство.',
    '梦见毒药的含义', '梦见毒药是什么意思？', '毒药象征毒性与背叛。',
    '毒の夢', '毒の夢は何を意味する？', '毒は有害性と裏切りを表す。',
    '독 꿈', '독 꿈은 무슨 의미일까?', '독은 유독성과 배신을 나타냅니다.',
    'Zehir rüyası', 'Zehir görmek ne anlama gelir?', 'Zehir toksisiteyi ve ihaneti simgeler.',
    'ज़हर का सपना', 'सपने में ज़हर क्या मतलब?', 'ज़हर विषाक्तता और विश्वासघात का प्रतीक है।',
    'Sogno di veleno', 'Cosa significa sognare il veleno?', 'Il veleno rappresenta tossicità e tradimento.',
  ],
  weapon: [
    'Weapon Dream Meaning', 'What Does It Mean to Dream About a Weapon?', 'A weapon symbolizes power, defense, and conflict you are prepared to face.',
    'تفسير حلم السلاح', 'ما معنى رؤية السلاح في الحلم؟', 'السلاح يرمز للقوة والدفاع والصراع اللي إنت مستعد تواجهه.',
    'Soñar con arma', '¿Qué significa soñar con arma?', 'El arma simboliza poder y defensa.',
    'Rêve d’arme', 'Que signifie rêver d’arme?', 'L’arme symbolise pouvoir et défense.',
    'Waffe im Traum', 'Was bedeutet Waffe im Traum?', 'Eine Waffe symbolisiert Macht und Verteidigung.',
    'Sonhar com arma', 'O que significa sonhar com arma?', 'A arma representa poder e defesa.',
    'Сон об оружии', 'Что значит сон об оружии?', 'Оружие символизирует силу и защиту.',
    '梦见武器的含义', '梦见武器是什么意思？', '武器象征力量与防御。',
    '武器の夢', '武器の夢は何を意味する？', '武器は力と防御を表す。',
    '무기 꿈', '무기 꿈은 무슨 의미일까?', '무기는 힘과 방어를 나타냅니다.',
    'Silah rüyası', 'Silah görmek ne anlama gelir?', 'Silah gücü ve savunmayı simgeler.',
    'हथियार का सपना', 'सपने में हथियार क्या मतलब?', 'हथियार शक्ति और रक्षा का प्रतीक है।',
    'Sogno di arma', 'Cosa significa sognare l’arma?', 'L’arma rappresenta potere e difesa.',
  ],
};
