// 13 languages order: en, ar, es, fr, de, pt, ru, zh, ja, ko, tr, hi, it
// Each symbol: [en_t,en_h,en_m, ar_t,ar_h,ar_m, es..., it (13x3 = 39 strings)]
// These are NEW symbols not present in core SYM / batch2.
export const BATCH3_SYMBOLS = {
  hair: [
    'Hair Dream Meaning', 'What Does It Mean to Dream About Hair?', 'Hair in dreams relates to strength, identity, and how you present yourself to the world.',
    'تفسير حلم الشعر', 'ما معنى رؤية الشعر في الحلم؟', 'الشعر في الحلم يرتبط بالقوة والهوية والطريقة اللي بتظهر بيها لنفسك.',
    'Soñar con cabello', '¿Qué significa soñar con cabello?', 'El cabello se relaciona con la fuerza y la identidad.',
    'Rêve de cheveux', 'Que signifie rêver de cheveux?', 'Les cheveux renvoient à la force et à l’identité.',
    'Haar im Traum', 'Was bedeutet Haar im Traum?', 'Haar hängt mit Stärke und Identität zusammen.',
    'Sonhar com cabelo', 'O que significa sonhar com cabelo?', 'O cabelo está ligado à força e identidade.',
    'Сон о волосах', 'Что значит сон о волосах?', 'Волосы связаны с силой и идентичностью.',
    '梦见头发的含义', '梦见头发是什么意思？', '头发与力量和自我形象相关。',
    '髪の夢', '髪の夢は何を意味する？', '髪は力とアイデンティティを表す。',
    '머리카락 꿈', '머리카락 꿈은 무슨 의미일까?', '머리카락은 힘과 정체성을 나타냅니다.',
    'Saç rüyası', 'Saç görmek ne anlama gelir?', 'Saç güç ve kimlikle ilgilidir.',
    'बालों का सपना', 'सपने में बाल क्या मतलब?', 'बाल शक्ति और पहचान से जुड़े हैं।',
    'Sogno di capelli', 'Cosa significa sognare i capelli?', 'I capelli riguardano forza e identità.',
  ],
  eye: [
    'Eye Dream Meaning', 'What Does It Mean to Dream About Eyes?', 'Eyes symbolize perception, awareness, and the truth you are beginning to see.',
    'تفسير حلم العين', 'ما معنى رؤية العين في الحلم؟', 'العين ترمز للإدراك والوعي والحقيقة اللي بدأت تبصرها.',
    'Soñar con ojos', '¿Qué significa soñar con ojos?', 'Los ojos simbolizan la percepción y la verdad.',
    'Rêve d’yeux', 'Que signifie rêver d’yeux?', 'Les yeux symbolisent la perception et la vérité.',
    'Augen im Traum', 'Was bedeutet Auge im Traum?', 'Augen symbolisieren Wahrnehmung und Wahrheit.',
    'Sonhar com olhos', 'O que significa sonhar com olhos?', 'Os olhos representam percepção e verdade.',
    'Сон о глазах', 'Что значит сон о глазах?', 'Глаза символизируют восприятие и истину.',
    '梦见眼睛的含义', '梦见眼睛是什么意思？', '眼睛象征觉察与真相。',
    '目の夢', '目の夢は何を意味する？', '目は知覚と真実を表す。',
    '눈 꿈', '눈 꿈은 무슨 의미일까?', '눈은 지각과 진실을 나타냅니다.',
    'Göz rüyası', 'Göz görmek ne anlama gelir?', 'Gözler algıyı ve gerçeği simgeler.',
    'आँखों का सपना', 'सपने में आँखें क्या मतलब?', 'आँखें जागरूकता और सच का प्रतीक हैं।',
    'Sogno di occhi', 'Cosa significa sognare gli occhi?', 'Gli occhi rappresentano percezione e verità.',
  ],
  hand: [
    'Hand Dream Meaning', 'What Does It Mean to Dream About Hands?', 'Hands symbolize action, capability, and your ability to shape your own life.',
    'تفسير حلم اليد', 'ما معنى رؤية اليد في الحلم؟', 'اليد ترمز للعمل والقدرة وطريقتك في تشكيل حياتك.',
    'Soñar con manos', '¿Qué significa soñar con manos?', 'Las manos simbolizan la acción y el poder.',
    'Rêve de mains', 'Que signifie rêver de mains?', 'Les mains symbolisent l’action et la capacité.',
    'Hände im Traum', 'Was bedeutet Hand im Traum?', 'Hände symbolisieren Handeln und Fähigkeit.',
    'Sonhar com mãos', 'O que significa sonhar com mãos?', 'As mãos representam ação e capacidade.',
    'Сон о руках', 'Что значит сон о руках?', 'Руки символизируют действие и способность.',
    '梦见手的含义', '梦见手是什么意思？', '手象征行动与能力。',
    '手の夢', '手の夢は何を意味する？', '手は行動と能力を表す。',
    '손 꿈', '손 꿈은 무슨 의미일까?', '손은 행동과 능력을 나타냅니다.',
    'El rüyası', 'El görmek ne anlama gelir?', 'Eller eylemi ve yeteneği simgeler.',
    'हाथों का सपना', 'सपने में हाथ क्या मतलब?', 'हाथ क्रिया और क्षमता का प्रतीक हैं।',
    'Sogno di mani', 'Cosa significa sognare le mani?', 'Le mani rappresentano azione e capacità.',
  ],
  thief: [
    'Thief Dream Meaning', 'What Does It Mean to Dream About a Thief?', 'A thief in dreams points to fears of loss, betrayal, or something taken from you without consent.',
    'تفسير حلم اللص', 'ما معنى رؤية اللص في الحلم؟', 'اللص يشير لخوفك من الخسارة أو الخيانة أو شيء أُخذ منك رغماً عنك.',
    'Soñar con ladrón', '¿Qué significa soñar con un ladrón?', 'El ladrón apunta a miedo a la pérdida o traición.',
    'Rêve de voleur', 'Que signifie rêver de voleur?', 'Le voleur évoque peur de la perte ou trahison.',
    'Dieb im Traum', 'Was bedeutet ein Dieb im Traum?', 'Ein Dieb weist auf Verlustangst oder Verrat hin.',
    'Sonhar com ladrão', 'O que significa sonhar com ladrão?', 'O ladrão aponta medo de perda ou traição.',
    'Сон о воре', 'Что значит сон о воре?', 'Вор указывает на страх потери или предательства.',
    '梦见小偷的含义', '梦见小偷是什么意思？', '小偷象征对失去或被背叛的恐惧。',
    '泥棒の夢', '泥棒の夢は何を意味する？', '泥棒は損失や裏切りの恐れを表す。',
    '도둑 꿈', '도둑 꿈은 무슨 의미일까?', '도둑은 잃거나 배신당할 두려움을 나타냅니다.',
    'Hırsız rüyası', 'Hırsız görmek ne anlama gelir?', 'Hırsız kayıp veya ihanet korkusunu simgeler.',
    'चोर का सपना', 'सपने में चोर क्या मतलब?', 'चोर हानि या विश्वासघात का डर दिखाता है।',
    'Sogno di ladro', 'Cosa significa sognare un ladro?', 'Il ladro indica paura di perdita o tradimento.',
  ],
  police: [
    'Police Dream Meaning', 'What Does It Mean to Dream About Police?', 'Police represent authority, rules, and your own conscience or need for order.',
    'تفسير حلم الشرطة', 'ما معنى رؤية الشرطة في الحلم؟', 'الشرطة تمثل السلطة والقواعد وضميرك أو حاجتك للنظام.',
    'Soñar con policía', '¿Qué significa soñar con policía?', 'La policía representa autoridad y orden.',
    'Rêve de police', 'Que signifie rêver de police?', 'La police symbolise autorité et ordre.',
    'Polizei im Traum', 'Was bedeutet Polizei im Traum?', 'Die Polizei symbolisiert Autorität und Ordnung.',
    'Sonhar com polícia', 'O que significa sonhar com polícia?', 'A polícia representa autoridade e ordem.',
    'Сон о полиции', 'Что значит сон о полиции?', 'Полиция символизирует власть и порядок.',
    '梦见警察的含义', '梦见警察是什么意思？', '警察象征权威与秩序。',
    '警察の夢', '警察の夢は何を意味する？', '警察は権威と秩序を表す。',
    '경찰 꿈', '경찰 꿈은 무슨 의미일까?', '경찰은 권위와 질서를 나타냅니다.',
    'Polis rüyası', 'Polis görmek ne anlama gelir?', 'Polis otorite ve düzeni simgeler.',
    'पुलिस का सपना', 'सपने में पुलिस क्या मतलब?', 'पुलिस अधिकार और व्यवस्था का प्रतीक है।',
    'Sogno di polizia', 'Cosa significa sognare la polizia?', 'La polizia rappresenta autorità e ordine.',
  ],
  tornado: [
    'Tornado Dream Meaning', 'What Does It Mean to Dream About a Tornado?', 'A tornado symbolizes chaos, sudden upheaval, and emotions spinning out of control.',
    'تفسير حلم الإعصار', 'ما معنى رؤية الإعصار في الحلم؟', 'الإعصار يرمز للفوضى والاضطراب المفاجئ والمشاعر اللي خرجت عن السيطرة.',
    'Soñar con tornado', '¿Qué significa soñar con un tornado?', 'El tornado simboliza caos y emoción descontrolada.',
    'Rêve de tornade', 'Que signifie rêver de tornade?', 'La tornade symbolise chaos et émotions folles.',
    'Tornado im Traum', 'Was bedeutet ein Tornado im Traum?', 'Ein Tornado symbolisiert Chaos und Kontrollverlust.',
    'Sonhar com tornado', 'O que significa sonhar com tornado?', 'O tornado representa caos e emoções fora de controle.',
    'Сон о торнадо', 'Что значит сон о торнадо?', 'Торнадо символизирует хаос и потерю контроля.',
    '梦见龙卷风的含义', '梦见龙卷风是什么意思？', '龙卷风象征混乱与失控。',
    '竜巻の夢', '竜巻の夢は何を意味する？', '竜巻は混沌と感情の暴走を表す。',
    '토네이도 꿈', '토네이도 꿈은 무슨 의미일까?', '토네이도는 혼돈과 감정 폭주를 나타냅니다.',
    'Kasırga rüyası', 'Kasırga görmek ne anlama gelir?', 'Kasırga kaos ve kontrol kaybını simgeler.',
    'बवंडर का सपना', 'सपने में बवंडर क्या मतलब?', 'बवंडर अराजकता और भावनाओं की बेकाबू का प्रतीक है।',
    'Sogno di tornado', 'Cosa significa sognare un tornado?', 'Il tornado rappresenta caos e mancanza di controllo.',
  ],
  snow: [
    'Snow Dream Meaning', 'What Does It Mean to Dream About Snow?', 'Snow symbolizes purity, stillness, and a period of quiet before renewal.',
    'تفسير حلم الثلج', 'ما معنى رؤية الثلج في الحلم؟', 'الثلج يرمز للنقاء والسكون وفترة هدوء قبل التجدد.',
    'Soñar con nieve', '¿Qué significa soñar con nieve?', 'La nieve simboliza pureza y quietud.',
    'Rêve de neige', 'Que signifie rêver de neige?', 'La neige symbolise pureté et calme.',
    'Schnee im Traum', 'Was bedeutet Schnee im Traum?', 'Schnee symbolisiert Reinheit und Stille.',
    'Sonhar com neve', 'O que significa sonhar com neve?', 'A neve representa pureza e quietude.',
    'Сон о снеге', 'Что значит сон о снеге?', 'Снег символизирует чистоту и покой.',
    '梦见雪的含义', '梦见雪是什么意思？', '雪象征纯洁与静谧。',
    '雪の夢', '雪の夢は何を意味する？', '雪は清らかさと静けさを表す。',
    '눈 꿈', '눈 꿈은 무슨 의미일까?', '눈은 순수와 고요를 나타냅니다.',
    'Kar rüyası', 'Kar görmek ne anlama gelir?', 'Kar saflığı ve sessizliği simgeler.',
    'बर्फ का सपना', 'सपने में बर्फ क्या मतलब?', 'बर्फ शुद्धता और शांति का प्रतीक है।',
    'Sogno di neve', 'Cosa significa sognare la neve?', 'La neve rappresenta purezza e quiete.',
  ],
  forest: [
    'Forest Dream Meaning', 'What Does It Mean to Dream About a Forest?', 'A forest symbolizes the unknown, mystery, and exploring the deeper parts of your mind.',
    'تفسير حلم الغابة', 'ما معنى رؤية الغابة في الحلم؟', 'الغابة ترمز للمجهول والغموض واستكشاف أعماق عقلك.',
    'Soñar con bosque', '¿Qué significa soñar con un bosque?', 'El bosque simboliza lo desconocido y misterioso.',
    'Rêve de forêt', 'Que signifie rêver de forêt?', 'La forêt symbolise l’inconnu et le mystère.',
    'Wald im Traum', 'Was bedeutet ein Wald im Traum?', 'Ein Wald symbolisiert Unbekanntes und Geheimnis.',
    'Sonhar com floresta', 'O que significa sonhar com floresta?', 'A floresta representa o desconhecido e mistério.',
    'Сон о лесе', 'Что значит сон о лесе?', 'Лес символизирует неизвестное и тайну.',
    '梦见森林的含义', '梦见森林是什么意思？', '森林象征未知与神秘。',
    '森の夢', '森の夢は何を意味する？', '森は未知と神秘を表す。',
    '숲 꿈', '숲 꿈은 무슨 의미일까?', '숲은 미지와 신비를 나타냅니다.',
    'Orman rüyası', 'Orman görmek ne anlama gelir?', 'Orman bilinmeyen ve gizemi simgeler.',
    'जंगल का सपना', 'सपने में जंगल क्या मतलब?', 'जंगल अज्ञात और रहस्य का प्रतीक है।',
    'Sogno di foresta', 'Cosa significa sognare una foresta?', 'La foresta rappresenta l’ignoto e il mistero.',
  ],
  bridge: [
    'Bridge Dream Meaning', 'What Does It Mean to Dream About a Bridge?', 'A bridge symbolizes transition, connection, and moving from one life phase to another.',
    'تفسير حلم الجسر', 'ما معنى رؤية الجسر في الحلم؟', 'الجسر يرمز للانتقال والاتصال والتحرك من مرحلة لحياة لأخرى.',
    'Soñar con puente', '¿Qué significa soñar con un puente?', 'El puente simboliza transición y conexión.',
    'Rêve de pont', 'Que signifie rêver de pont?', 'Le pont symbolise transition et lien.',
    'Brücke im Traum', 'Was bedeutet eine Brücke im Traum?', 'Eine Brücke symbolisiert Übergang und Verbindung.',
    'Sonhar com ponte', 'O que significa sonhar com ponte?', 'A ponte representa transição e conexão.',
    'Сон о мосте', 'Что значит сон о мосте?', 'Мост символизирует переход и связь.',
    '梦见桥的含义', '梦见桥是什么意思？', '桥象征过渡与连接。',
    '橋の夢', '橋の夢は何を意味する？', '橋は移行とつながりを表す。',
    '다리 꿈', '다리 꿈은 무슨 의미일까?', '다리는 전환과 연결을 나타냅니다.',
    'Köprü rüyası', 'Köprü görmek ne anlama gelir?', 'Köprü geçişi ve bağı simgeler.',
    'पुल का सपना', 'सपने में पुल क्या मतलब?', 'पुल संक्रमण और जुड़ाव का प्रतीक है।',
    'Sogno di ponte', 'Cosa significa sognare un ponte?', 'Il ponte rappresenta transizione e connessione.',
  ],
  train: [
    'Train Dream Meaning', 'What Does It Mean to Dream About a Train?', 'A train symbolizes your life journey, momentum, and the direction you are heading.',
    'تفسير حلم القطار', 'ما معنى رؤية القطار في الحلم؟', 'القطار يرمز لرحلة حياتك والزخم والاتجاه اللي رايحله.',
    'Soñar con tren', '¿Qué significa soñar con un tren?', 'El tren simboliza el viaje de vida y el rumbo.',
    'Rêve de train', 'Que signifie rêver de train?', 'Le train symbolise le parcours de vie.',
    'Zug im Traum', 'Was bedeutet ein Zug im Traum?', 'Ein Zug symbolisiert Lebensreise und Richtung.',
    'Sonhar com trem', 'O que significa sonhar com trem?', 'O trem representa a jornada e a direção.',
    'Сон о поезде', 'Что значит сон о поезде?', 'Поезд символизирует жизненный путь и направление.',
    '梦见火车的含义', '梦见火车是什么意思？', '火车象征人生旅程与方向。',
    '電車の夢', '電車の夢は何を意味する？', '電車は人生の旅と方向を表す。',
    '기차 꿈', '기차 꿈은 무슨 의미일까?', '기차는 삶의 여정과 방향을 나타냅니다.',
    'Tren rüyası', 'Tren görmek ne anlama gelir?', 'Tren yaşam yolculuğunu ve yönü simgeler.',
    'ट्रेन का सपना', 'सपने में ट्रेन क्या मतलब?', 'ट्रेन जीवन यात्रा और दिशा का प्रतीक है।',
    'Sogno di treno', 'Cosa significa sognare un treno?', 'Il treno rappresenta il viaggio e la direzione.',
  ],
  airplane: [
    'Airplane Dream Meaning', 'What Does It Mean to Dream About an Airplane?', 'An airplane symbolizes ambition, escape, and rapid progress toward a big goal.',
    'تفسير حلم الطائرة', 'ما معنى رؤية الطائرة في الحلم؟', 'الطائرة ترمز للطموح والهروب والتقدم السريع نحو هدف كبير.',
    'Soñar con avión', '¿Qué significa soñar con un avión?', 'El avión simboliza ambición y escape.',
    'Rêve d’avion', 'Que signifie rêver d’avion?', 'L’avion symbolise ambition et évasion.',
    'Flugzeug im Traum', 'Was bedeutet ein Flugzeug im Traum?', 'Ein Flugzeug symbolisiert Ehrgeiz und Flucht.',
    'Sonhar com avião', 'O que significa sonhar com avião?', 'O avião representa ambição e escape.',
    'Сон о самолете', 'Что значит сон о самолете?', 'Самолет символизирует амбицию и побег.',
    '梦见飞机的含义', '梦见飞机是什么意思？', '飞机象征抱负与逃离。',
    '飛行機の夢', '飛行機の夢は何を意味する？', '飛行機は野心と脱出を表す。',
    '비행기 꿈', '비행기 꿈은 무슨 의미일까?', '비행기는 야망과 탈출을 나타냅니다.',
    'Uçak rüyası', 'Uçak görmek ne anlama gelir?', 'Uçak hırsı ve kaçışı simgeler.',
    'हवाई जहाज का सपना', 'सपने में हवाई जहाज क्या मतलब?', 'हवाई जहाज महत्वाकांक्षा और भागने का प्रतीक है।',
    'Sogno di aereo', 'Cosa significa sognare un aereo?', 'L’aereo rappresenta ambizione e fuga.',
  ],
  shopping: [
    'Shopping Dream Meaning', 'What Does It Mean to Dream About Shopping?', 'Shopping in dreams reflects how you seek value, choice, and fulfillment in life.',
    'تفسير حلم التسوق', 'ما معنى رؤية التسوق في الحلم؟', 'التسوق يعكس كيف تدوّر القيمة والاختيار والإشباع في حياتك.',
    'Soñar con comprar', '¿Qué significa soñar con comprar?', 'Comprar refleja la búsqueda de valor y realización.',
    'Rêve de shopping', 'Que signifie rêver de shopping?', 'Le shopping reflète la quête de valeur.',
    'Einkaufen im Traum', 'Was bedeutet Einkaufen im Traum?', 'Einkaufen spiegelt Suche nach Wert wider.',
    'Sonhar com compras', 'O que significa sonhar com compras?', 'As compras refletem busca por valor.',
    'Сон о шопинге', 'Что значит сон о шопинге?', 'Шопинг отражает поиск ценности.',
    '梦见购物的含义', '梦见购物是什么意思？', '购物反映对价值与满足的追求。',
    '買い物の夢', '買い物の夢は何を意味する？', '買い物は価値と満足の探求を表す。',
    '쇼핑 꿈', '쇼핑 꿈은 무슨 의미일까?', '쇼핑은 가치와 충족을 추구함을 나타냅니다.',
    'Alışveriş rüyası', 'Alışveriş görmek ne anlama gelir?', 'Alışveriş değer arayışını simgeler.',
    'शॉपिंग का सपना', 'सपने में शॉपिंग क्या मतलब?', 'शॉपिंग मूल्य और संतुष्टि की खोज है।',
    'Sogno di shopping', 'Cosa significa sognare di fare shopping?', 'Lo shopping riflette la ricerca di valore.',
  ],
  clock: [
    'Clock Dream Meaning', 'What Does It Mean to Dream About a Clock?', 'A clock symbolizes time, urgency, and your awareness of deadlines or aging.',
    'تفسير حلم الساعة', 'ما معنى رؤية الساعة في الحلم؟', 'الساعة ترمز للوقت والاستعجال وإدراكك للمواعيد أو التقدم في العمر.',
    'Soñar con reloj', '¿Qué significa soñar con un reloj?', 'El reloj simboliza el tiempo y la urgencia.',
    'Rêve d’horloge', 'Que signifie rêver d’horloge?', 'L’horloge symbolise le temps et l’urgence.',
    'Uhr im Traum', 'Was bedeutet eine Uhr im Traum?', 'Eine Uhr symbolisiert Zeit und Dringlichkeit.',
    'Sonhar com relógio', 'O que significa sonhar com relógio?', 'O relógio representa tempo e urgência.',
    'Сон о часах', 'Что значит сон о часах?', 'Часы символизируют время и срочность.',
    '梦见时钟的含义', '梦见时钟是什么意思？', '时钟象征时间与紧迫。',
    '時計の夢', '時計の夢は何を意味する？', '時計は時間と切迫を表す。',
    '시계 꿈', '시계 꿈은 무슨 의미일까?', '시계는 시간과 긴박함을 나타냅니다.',
    'Saat rüyası', 'Saat görmek ne anlama gelir?', 'Saat zamanı ve aciliyeti simgeler.',
    'घड़ी का सपना', 'सपने में घड़ी क्या मतलब?', 'घड़ी समय और तात्कालिकता का प्रतीक है।',
    'Sogno di orologio', 'Cosa significa sognare un orologio?', 'L’orologio rappresenta tempo e urgenza.',
  ],
  crown: [
    'Crown Dream Meaning', 'What Does It Mean to Dream About a Crown?', 'A crown symbolizes power, honor, self-worth, and recognition of your achievements.',
    'تفسير حلم التاج', 'ما معنى رؤية التاج في الحلم؟', 'التاج يرمز للسلطة والشرف وقيمتك الذاتية وتقدير إنجازاتك.',
    'Soñar con corona', '¿Qué significa soñar con una corona?', 'La corona simboliza poder y honor.',
    'Rêve de couronne', 'Que signifie rêver de couronne?', 'La couronne symbolise pouvoir et honneur.',
    'Krone im Traum', 'Was bedeutet eine Krone im Traum?', 'Eine Krone symbolisiert Macht und Ehre.',
    'Sonhar com coroa', 'O que significa sonhar com coroa?', 'A coroa representa poder e honra.',
    'Сон о короне', 'Что значит сон о короне?', 'Корона символизирует власть и честь.',
    '梦见王冠的含义', '梦见王冠是什么意思？', '王冠象征权力与荣耀。',
    '王冠の夢', '王冠の夢は何を意味する？', '王冠は権力と名誉を表す。',
    '왕관 꿈', '왕관 꿈은 무슨 의미일까?', '왕관은 권력과 명예를 나타냅니다.',
    'Tac rüyası', 'Tac görmek ne anlama gelir?', 'Tac gücü ve onuru simgeler.',
    'ताज का सपना', 'सपने में ताज क्या मतलब?', 'ताज शक्ति और सम्मान का प्रतीक है।',
    'Sogno di corona', 'Cosa significa sognare una corona?', 'La corona rappresenta potere e onore.',
  ],
  war: [
    'War Dream Meaning', 'What Does It Mean to Dream About War?', 'War in dreams reflects inner conflict, struggle, or a battle you are facing in waking life.',
    'تفسير حلم الحرب', 'ما معنى رؤية الحرب في الحلم؟', 'الحرب تعكس صراعاً داخلياً أو معركة بتواجهها في حياتك اليقظة.',
    'Soñar con guerra', '¿Qué significa soñar con guerra?', 'La guerra refleja conflicto interno y lucha.',
    'Rêve de guerre', 'Que signifie rêver de guerre?', 'La guerre reflète conflit intérieur et lutte.',
    'Krieg im Traum', 'Was bedeutet Krieg im Traum?', 'Krieg spiegelt inneren Konflikt und Kampf wider.',
    'Sonhar com guerra', 'O que significa sonhar com guerra?', 'A guerra reflete conflito interno e luta.',
    'Сон о войне', 'Что значит сон о войне?', 'Война отражает внутренний конфликт и борьбу.',
    '梦见战争的含义', '梦见战争是什么意思？', '战争象征内心冲突与挣扎。',
    '戦争の夢', '戦争の夢は何を意味する？', '戦争は内なる葛藤と闘いを表す。',
    '전쟁 꿈', '전쟁 꿈은 무슨 의미일까?', '전쟁은 내면의 갈등과 싸움을 나타냅니다.',
    'Savaş rüyası', 'Savaş görmek ne anlama gelir?', 'Savaş içsel çatışma ve mücadeleyi simgeler.',
    'युद्ध का सपना', 'सपने में युद्ध क्या मतलब?', 'युद्ध आंतरिक संघर्ष और संघर्ष का प्रतीक है।',
    'Sogno di guerra', 'Cosa significa sognare la guerra?', 'La guerra riflette conflitto interiore e lotta.',
  ],
  candle: [
    'Candle Dream Meaning', 'What Does It Mean to Dream About a Candle?', 'A candle symbolizes hope, guidance, and a small light in times of darkness.',
    'تفسير حلم الشمعة', 'ما معنى رؤية الشمعة في الحلم؟', 'الشمعة ترمز للأمل والهداية وضوء صغير في أوقات الظلام.',
    'Soñar con vela', '¿Qué significa soñar con una vela?', 'La vela simboliza esperanza y guía.',
    'Rêve de bougie', 'Que signifie rêver de bougie?', 'La bougie symbolise espoir et guidance.',
    'Kerze im Traum', 'Was bedeutet eine Kerze im Traum?', 'Eine Kerze symbolisiert Hoffnung und Führung.',
    'Sonhar com vela', 'O que significa sonhar com vela?', 'A vela representa esperança e guia.',
    'Сон о свече', 'Что значит сон о свече?', 'Свеча символизирует надежду и свет.',
    '梦见蜡烛的含义', '梦见蜡烛是什么意思？', '蜡烛象征希望与指引。',
    '蝋燭の夢', '蝋燭の夢は何を意味する？', '蝋燭は希望と導きを表す。',
    '촛불 꿈', '촛불 꿈은 무슨 의미일까?', '촛불은 희망과 인도를 나타냅니다.',
    'Mum rüyası', 'Mum görmek ne anlama gelir?', 'Mum umudu ve rehberliği simgeler.',
    'मोमबत्ती का सपना', 'सपने में मोमबत्ती क्या मतलब?', 'मोमबत्ती आशा और मार्गदर्शन का प्रतीक है।',
    'Sogno di candela', 'Cosa significa sognare una candela?', 'La candela rappresenta speranza e guida.',
  ],
  island: [
    'Island Dream Meaning', 'What Does It Mean to Dream About an Island?', 'An island symbolizes isolation, independence, or a need for solitude and rest.',
    'تفسير حلم الجزيرة', 'ما معنى رؤية الجزيرة في الحلم؟', 'الجزيرة ترمز للعزلة والاستقلال أو حاجتك للوحدة والراحة.',
    'Soñar con isla', '¿Qué significa soñar con una isla?', 'La isla simboliza aislamiento y descanso.',
    'Rêve d’île', 'Que signifie rêver d’île?', 'L’île symbolise isolement et repos.',
    'Insel im Traum', 'Was bedeutet eine Insel im Traum?', 'Eine Insel symbolisiert Isolation und Ruhe.',
    'Sonhar com ilha', 'O que significa sonhar com ilha?', 'A ilha representa isolamento e descanso.',
    'Сон об острове', 'Что значит сон об острове?', 'Остров символизирует изоляцию и покой.',
    '梦见岛屿的含义', '梦见岛屿是什么意思？', '岛屿象征孤独与休息。',
    '島の夢', '島の夢は何を意味する？', '島は孤立と休息を表す。',
    '섬 꿈', '섬 꿈은 무슨 의미일까?', '섬은 고독과 휴식을 나타냅니다.',
    'Ada rüyası', 'Ada görmek ne anlama gelir?', 'Ada yalnızlığı ve dinlenmeyi simgeler.',
    'द्वीप का सपना', 'सपने में द्वीप क्या मतलब?', 'द्वीप अलगाव और आराम का प्रतीक है।',
    'Sogno di isola', 'Cosa significa sognare un’isola?', 'L’isola rappresenta isolamento e riposo.',
  ],
  stairs: [
    'Stairs Dream Meaning', 'What Does It Mean to Dream About Stairs?', 'Stairs symbolize progress, levels of growth, and moving up or down in life.',
    'تفسير حلم السلالم', 'ما معنى رؤية السلالم في الحلم؟', 'السلالم ترمز للتقدم ومستويات النمو والصعود أو الهبوط في الحياة.',
    'Soñar con escaleras', '¿Qué significa soñar con escaleras?', 'Las escaleras simbolizan progreso y crecimiento.',
    'Rêve d’escaliers', 'Que signifie rêver d’escaliers?', 'Les escaliers symbolisent progrès et croissance.',
    'Treppe im Traum', 'Was bedeutet eine Treppe im Traum?', 'Eine Treppe symbolisiert Fortschritt und Wachstum.',
    'Sonhar com escadas', 'O que significa sonhar com escadas?', 'As escadas representam progresso e crescimento.',
    'Сон о лестнице', 'Что значит сон о лестнице?', 'Лестница символизирует прогресс и рост.',
    '梦见楼梯的含义', '梦见楼梯是什么意思？', '楼梯象征进步与成长。',
    '階段の夢', '階段の夢は何を意味する？', '階段は進歩と成長を表す。',
    '계단 꿈', '계단 꿈은 무슨 의미일까?', '계단은 진보와 성장을 나타냅니다.',
    'Merdiven rüyası', 'Merdiven görmek ne anlama gelir?', 'Merdiven ilerlemeyi ve büyümeyi simgeler.',
    'सीढ़ियों का सपना', 'सपने में सीढ़ियाँ क्या मतलब?', 'सीढ़ियाँ प्रगति और विकास का प्रतीक हैं।',
    'Sogno di scale', 'Cosa significa sognare le scale?', 'Le scale rappresentano progresso e crescita.',
  ],
  gun: [
    'Gun Dream Meaning', 'What Does It Mean to Dream About a Gun?', 'A gun symbolizes aggression, power, fear, or a sudden confrontation in your life.',
    'تفسير حلم المسدس', 'ما معنى رؤية المسدس في الحلم؟', 'المسدس يرمز للعدوان أو القوة أو الخوف أو مواجهة مفاجئة في حياتك.',
    'Soñar con pistola', '¿Qué significa soñar con una pistola?', 'La pistola simboliza agresión y miedo.',
    'Rêve de pistolet', 'Que signifie rêver de pistolet?', 'Le pistolet symbolise agression et peur.',
    'Waffe im Traum', 'Was bedeutet eine Waffe im Traum?', 'Eine Waffe symbolisiert Aggression und Angst.',
    'Sonhar com arma', 'O que significa sonhar com arma?', 'A arma representa agressão e medo.',
    'Сон о пистолете', 'Что значит сон о пистолете?', 'Пистолет символизирует агрессию и страх.',
    '梦见枪的含义', '梦见枪是什么意思？', '枪象征攻击与恐惧。',
    '銃の夢', '銃の夢は何を意味する？', '銃は攻撃と恐怖を表す。',
    '총 꿈', '총 꿈은 무슨 의미일까?', '총은 공격과 두려움을 나타냅니다.',
    'Silah rüyası', 'Silah görmek ne anlama gelir?', 'Silah saldırıyı ve korkuyu simgeler.',
    'बंदूक का सपना', 'सपने में बंदूक क्या मतलब?', 'बंदूक हमले और डर का प्रतीक है।',
    'Sogno di pistola', 'Cosa significa sognare una pistola?', 'La pistola rappresenta aggressone e paura.',
  ],
  bed: [
    'Bed Dream Meaning', 'What Does It Mean to Dream About a Bed?', 'A bed symbolizes rest, intimacy, and the private space of your thoughts and relationships.',
    'تفسير حلم السرير', 'ما معنى رؤية السرير في الحلم؟', 'السرير يرمز للراحة والألفة والمساحة الخاصة بأفكارك وعلاقاتك.',
    'Soñar con cama', '¿Qué significa soñar con una cama?', 'La cama simboliza descanso e intimidad.',
    'Rêve de lit', 'Que signifie rêver de lit?', 'Le lit symbolise repos et intimité.',
    'Bett im Traum', 'Was bedeutet ein Bett im Traum?', 'Ein Bett symbolisiert Ruhe und Intimität.',
    'Sonhar com cama', 'O que significa sonhar com cama?', 'A cama representa descanso e intimidade.',
    'Сон о кровати', 'Что значит сон о кровати?', 'Кровать символизирует отдых и близость.',
    '梦见床的含义', '梦见床是什么意思？', '床象征休息与亲密。',
    'ベッドの夢', 'ベッドの夢は何を意味する？', 'ベッドは休息と親密さを表す。',
    '침대 꿈', '침대 꿈은 무슨 의미일까?', '침대는 휴식과 친밀함을 나타냅니다.',
    'Yatak rüyası', 'Yatak görmek ne anlama gelir?', 'Yatak dinlenmeyi ve yakınlığı simgeler.',
    'बिस्तर का सपना', 'सपने में बिस्तर क्या मतलब?', 'बिस्तर आराम और निकटता का प्रतीक है।',
    'Sogno di letto', 'Cosa significa sognare un letto?', 'Il letto rappresenta riposo e intimità.',
  ],
};
