/**
 * Localized symbol names + synonyms for search.
 * Each entry: the canonical slug (matches SYMBOL_LIST), plus a display name and
 * search aliases in several languages. The Symbols page searches across ALL of
 * these so e.g. "مفتاح" finds "key", "schlange" finds "snake", etc.
 */
export interface SymbolName {
  en: string;
  ar: string;
  /** Extra search aliases (any language) — lowercased at query time. */
  aliases?: string[];
}

export const SYMBOL_NAMES: Record<string, SymbolName> = {
  airplane: { en: 'airplane', ar: 'طائرة', aliases: ['plane', 'aeroplane', 'طيارة'] },
  ambulance: { en: 'ambulance', ar: 'إسعاف', aliases: ['سيارة إسعاف'] },
  arm: { en: 'arm', ar: 'ذراع', aliases: ['يد', 'ساعد'] },
  baby: { en: 'baby', ar: 'رضيع', aliases: ['infant', 'طفل', 'مولود'] },
  back: { en: 'back', ar: 'ظهر' },
  bag: { en: 'bag', ar: 'حقيبة', aliases: ['شنطة', 'حقيبة ظهر'] },
  bed: { en: 'bed', ar: 'سرير', aliases: ['فراش'] },
  being_chased: { en: 'being chased', ar: 'مطاردة', aliases: [' chased', 'مطارد', 'هرب'] },
  belly: { en: 'belly', ar: 'بطن', aliases: ['بطن'] },
  bird: { en: 'bird', ar: 'طائر', aliases: ['عصفور', 'طائر'] },
  blood: { en: 'blood', ar: 'دم', aliases: ['دماء'] },
  bone: { en: 'bone', ar: 'عظم', aliases: ['عظام'] },
  book: { en: 'book', ar: 'كتاب', aliases: ['مصحف', 'قرآن'] },
  bridge: { en: 'bridge', ar: 'جسر' },
  bus: { en: 'bus', ar: 'حافلة', aliases: ['باص', 'اتوبيس'] },
  candle: { en: 'candle', ar: 'شمعة', aliases: ['شموع'] },
  car: { en: 'car', ar: 'سيارة', aliases: ['عربية', 'سيارة'] },
  car_accident: { en: 'car accident', ar: 'حادث سيارة', aliases: ['حادث', 'تصادم'] },
  cat: { en: 'cat', ar: 'قطة', aliases: ['قطة', 'هر'] },
  chest: { en: 'chest', ar: 'صدر', aliases: ['صدر'] },
  child: { en: 'child', ar: 'طفل', aliases: ['ولد', 'بنت'] },
  clock: { en: 'clock', ar: 'ساعة', aliases: ['ساعة'] },
  clothes: { en: 'clothes', ar: 'ملابس', aliases: ['ثياب', 'لبس'] },
  cloud: { en: 'cloud', ar: 'غيم', aliases: ['سحابة', 'غيمة'] },
  crown: { en: 'crown', ar: 'تاج', aliases: ['عرش'] },
  crying: { en: 'crying', ar: 'بكاء', aliases: ['بكاء', 'دموع'] },
  dark: { en: 'dark', ar: 'ظلام', aliases: ['عتمة', 'ليل'] },
  dead_person: { en: 'dead person', ar: 'شخص ميت', aliases: ['ميت', 'جثة'] },
  death: { en: 'death', ar: 'موت', aliases: ['موت', 'وفاة'] },
  death_family: { en: 'death of family', ar: 'موت أحد الأقارب', aliases: ['وفاة قريب'] },
  desert: { en: 'desert', ar: 'صحراء', aliases: ['صحراء'] },
  doctor: { en: 'doctor', ar: 'طبيب', aliases: ['دكتور'] },
  dog: { en: 'dog', ar: 'كلب', aliases: ['كلب'] },
  dog_attack: { en: 'dog attack', ar: 'هجوم كلب', aliases: ['عضة كلب'] },
  door: { en: 'door', ar: 'باب', aliases: ['باب'] },
  ear: { en: 'ear', ar: 'أذن', aliases: ['أذن'] },
  earthquake: { en: 'earthquake', ar: 'زلزال', aliases: ['هزة أرضية'] },
  egg: { en: 'egg', ar: 'بيضة', aliases: ['بيض'] },
  elbow: { en: 'elbow', ar: 'كوع' },
  exam: { en: 'exam', ar: 'امتحان', aliases: ['اختبار', 'test'] },
  eye: { en: 'eye', ar: 'عين', aliases: ['عين', 'عيون'] },
  falling: { en: 'falling', ar: 'سقوط', aliases: ['يسقط', 'سقوط'] },
  father: { en: 'father', ar: 'أب', aliases: ['أب', 'والد'] },
  fighting: { en: 'fighting', ar: 'قتال', aliases: ['شجار', 'عراك'] },
  finger: { en: 'finger', ar: 'إصبع', aliases: ['أصابع'] },
  fire: { en: 'fire', ar: 'نار', aliases: ['حريق', 'نار'] },
  fire_burn: { en: 'fire / burn', ar: 'حريق أو حرق', aliases: ['حرق'] },
  fish: { en: 'fish', ar: 'سمكة', aliases: ['سمك'] },
  flood: { en: 'flood', ar: 'فيضان', aliases: ['غرق'] },
  flower: { en: 'flower', ar: 'زهرة', aliases: ['وردة', 'زهور'] },
  flying: { en: 'flying', ar: 'طيران', aliases: ['يطير', 'تحليق'] },
  flying_high: { en: 'flying high', ar: 'طيران عالٍ', aliases: ['ارتفاع'] },
  food: { en: 'food', ar: 'طعام', aliases: ['أكل', 'وجبة'] },
  foot: { en: 'foot', ar: 'قدم', aliases: ['أقدام', 'رجل'] },
  forest: { en: 'forest', ar: 'غابة', aliases: ['غابة'] },
  friend: { en: 'friend', ar: 'صديق', aliases: ['صديق', 'صديقة'] },
  ghost: { en: 'ghost', ar: 'شبح', aliases: ['جن', 'روح'] },
  gold: { en: 'gold', ar: 'ذهب', aliases: ['ذهب'] },
  gun: { en: 'gun', ar: 'مسدس', aliases: ['سلاح', 'بندقية', 'رصاص'] },
  hair: { en: 'hair', ar: 'شعر', aliases: ['شعر'] },
  hand: { en: 'hand', ar: 'يد', aliases: ['يدين', 'كف'] },
  heart: { en: 'heart', ar: 'قلب', aliases: ['قلب'] },
  horse: { en: 'horse', ar: 'حصان', aliases: ['حصان'] },
  hospital: { en: 'hospital', ar: 'مستشفى', aliases: ['مشفى'] },
  house: { en: 'house', ar: 'بيت', aliases: ['منزل', 'بيت'] },
  house_old: { en: 'old house', ar: 'بيت قديم', aliases: ['منزل قديم'] },
  injection: { en: 'injection', ar: 'حقنة', aliases: ['إبرة'] },
  island: { en: 'island', ar: 'جزيرة', aliases: ['جزيرة'] },
  key: { en: 'key', ar: 'مفتاح', aliases: ['مفتاح', 'مفاتيح'] },
  king: { en: 'king', ar: 'ملك', aliases: ['ملك'] },
  kissing: { en: 'kissing', ar: 'قُبلة', aliases: ['قبلة', 'تقبيل'] },
  knee: { en: 'knee', ar: 'ركبة', aliases: ['ركبة'] },
  knife: { en: 'knife', ar: 'سكين', aliases: ['سكينة'] },
  laughing: { en: 'laughing', ar: 'ضحك', aliases: ['ضحك'] },
  leg: { en: 'leg', ar: 'ساق', aliases: ['ساقين', 'رجل'] },
  light: { en: 'light', ar: 'ضوء', aliases: ['نور', 'إضاءة'] },
  lion: { en: 'lion', ar: 'أسد', aliases: ['أسد'] },
  losing_teeth: { en: 'losing teeth', ar: 'سقوط الأسنان', aliases: ['تساقط الأسنان'] },
  market: { en: 'market', ar: 'سوق', aliases: ['سوق'] },
  marriage: { en: 'marriage', ar: 'زواج', aliases: ['عرس', 'زواج'] },
  marriage_broken: { en: 'broken marriage', ar: 'زواج منهار', aliases: ['طلاق'] },
  medicine: { en: 'medicine', ar: 'دواء', aliases: ['علاج'] },
  mirror: { en: 'mirror', ar: 'مرآة', aliases: ['مرآة'] },
  money: { en: 'money', ar: 'مال', aliases: ['نقود', 'فلوس', 'دراهم'] },
  money_lost: { en: 'lost money', ar: 'مال مفقود', aliases: ['سرقة مال'] },
  money_steal: { en: 'stolen money', ar: 'سرقة مال', aliases: ['سرقة'] },
  moon: { en: 'moon', ar: 'قمر', aliases: ['قمر', 'بدر'] },
  moon_eclipse: { en: 'moon eclipse', ar: 'خسوف', aliases: ['خسوف قمر'] },
  mother: { en: 'mother', ar: 'أم', aliases: ['أم', 'والدة'] },
  motorcycle: { en: 'motorcycle', ar: 'دراجة نارية', aliases: ['موتوسيكل'] },
  mountain: { en: 'mountain', ar: 'جبل', aliases: ['جبل'] },
  mouth: { en: 'mouth', ar: 'فم', aliases: ['فم'] },
  naked: { en: 'naked', ar: 'عراة', aliases: ['عري', 'عاري'] },
  neck: { en: 'neck', ar: 'رقبة', aliases: ['عنق'] },
  nose: { en: 'nose', ar: 'أنف', aliases: ['أنف'] },
  nurse: { en: 'nurse', ar: 'ممرضة', aliases: ['ممرض'] },
  ocean: { en: 'ocean', ar: 'محيط', aliases: ['محيط'] },
  phone: { en: 'phone', ar: 'هاتف', aliases: ['جوال', 'موبايل', 'تليفون'] },
  poison: { en: 'poison', ar: 'سم', aliases: ['سم'] },
  police: { en: 'police', ar: 'شرطة', aliases: ['بوليس', 'شرطي'] },
  pregnancy: { en: 'pregnancy', ar: 'حمل', aliases: ['حامل', 'حمل'] },
  pregnancy_test: { en: 'pregnancy test', ar: 'اختبار حمل', aliases: ['تحليل حمل'] },
  prison: { en: 'prison', ar: 'سجن', aliases: ['حبس'] },
  queen: { en: 'queen', ar: 'ملكة', aliases: ['ملكة'] },
  rain: { en: 'rain', ar: 'مطر', aliases: ['مطر'] },
  ring: { en: 'ring', ar: 'خاتم', aliases: ['خاتم'] },
  road: { en: 'road', ar: 'طريق', aliases: ['شارع'] },
  running: { en: 'running', ar: 'جري', aliases: ['ركض'] },
  scar: { en: 'scar', ar: 'ندبة', aliases: ['أثر'] },
  school: { en: 'school', ar: 'مدرسة', aliases: ['مدرسة'] },
  sea: { en: 'sea', ar: 'بحر', aliases: ['بحر'] },
  shoe: { en: 'shoe', ar: 'حذاء', aliases: ['حذاء', 'جزمة'] },
  shopping: { en: 'shopping', ar: 'تسوق', aliases: ['تسوق'] },
  shoulder: { en: 'shoulder', ar: 'كتف', aliases: ['كتف'] },
  skin: { en: 'skin', ar: 'جلد', aliases: ['بشرة'] },
  smoke: { en: 'smoke', ar: 'دخان', aliases: ['تدخين'] },
  snake: { en: 'snake', ar: 'ثعبان', aliases: ['أفعى', 'حية', 'serpiente', 'serpent', 'schlange', 'cobra', 'viper'] },
  snake_bite: { en: 'snake bite', ar: 'لدغ ثعبان', aliases: ['لدغ'] },
  snake_many: { en: 'many snakes', ar: 'ثعابين كثيرة', aliases: ['افاعي'] },
  snow: { en: 'snow', ar: 'ثلج', aliases: ['ثلج'] },
  spider: { en: 'spider', ar: 'عنكبوت', aliases: ['عنكبوت'] },
  stairs: { en: 'stairs', ar: 'سلالم', aliases: ['درج'] },
  star: { en: 'star', ar: 'نجمة', aliases: ['نجمة', 'نجوم'] },
  storm: { en: 'storm', ar: 'عاصفة', aliases: ['رياح'] },
  stranger: { en: 'stranger', ar: 'غريب', aliases: ['شخص غريب'] },
  sun: { en: 'sun', ar: 'شمس', aliases: ['شمس'] },
  sun_rise: { en: 'sunrise', ar: 'شروق الشمس', aliases: ['فجر'] },
  surgery: { en: 'surgery', ar: 'عملية جراحية', aliases: ['عملية'] },
  teeth: { en: 'teeth', ar: 'أسنان', aliases: ['سن', 'أسنان'] },
  teeth_fall: { en: 'teeth falling', ar: 'سقوط الأسنان', aliases: ['تساقط الأسنان'] },
  teeth_falling: { en: 'teeth falling', ar: 'سقوط الأسنان', aliases: ['تساقط الأسنان'] },
  thief: { en: 'thief', ar: 'لص', aliases: ['سرقة'] },
  tongue: { en: 'tongue', ar: 'لسان', aliases: ['لسان'] },
  tornado: { en: 'tornado', ar: 'إعصار', aliases: ['زوبعة'] },
  train: { en: 'train', ar: 'قطار', aliases: ['قطار'] },
  tree: { en: 'tree', ar: 'شجرة', aliases: ['شجرة'] },
  tree_dead: { en: 'dead tree', ar: 'شجرة ميتة', aliases: ['شجرة يابسة'] },
  wallet: { en: 'wallet', ar: 'محفظة', aliases: ['محفظة'] },
  war: { en: 'war', ar: 'حرب', aliases: ['قتال'] },
  water: { en: 'water', ar: 'ماء', aliases: ['ماء', 'بحر', 'نهر'] },
  water_drink: { en: 'drinking water', ar: 'شرب الماء', aliases: ['ماء'] },
  water_flood: { en: 'water flood', ar: 'فيضان', aliases: ['غرق'] },
  weapon: { en: 'weapon', ar: 'سلاح', aliases: ['سلاح'] },
  wedding: { en: 'wedding', ar: 'زفاف', aliases: ['عرس', 'زواج'] },
  winning: { en: 'winning', ar: 'فوز', aliases: ['نجاح'] },
  wound: { en: 'wound', ar: 'جرح', aliases: ['جراح'] },
};
