/**
 * Localized symbol names + synonyms for search.
 * Each entry: the canonical slug (matches SYMBOL_LIST), plus a display name and
 * search aliases in several languages. The Symbols page searches across ALL of
 * these so e.g. "مفتاح" finds "key", "schlange" finds "snake", etc.
 */
export interface SymbolName {
  en: string;
  ar: string;
  /** Extra search aliases (any language) — lowercased at query time. */
  aliases?: string[];
  /** Per-locale translations. Optional, only set for locales that have been translated. */
  [locale: string]: string | string[] | undefined;
}

export const SYMBOL_NAMES: Record<string, SymbolName> = {
  airplane: { en: 'airplane', ar: 'طائرة', lt: 'lėktuvas', aliases: ['plane', 'aeroplane', 'طيارة'] },
  ambulance: { en: 'ambulance', ar: 'إسعاف', el: 'ασθενοφόρο', lt: 'greitoji', aliases: ['سيارة إسعاف'] },
  arm: { en: 'arm', ar: 'ذراع', el: 'χέρι', aliases: ['يد', 'ساعد'] },
  baby: { en: 'baby', ar: 'رضيع', el: 'μωρό', aliases: ['infant', 'طفل', 'مولود'] },
  back: { en: 'back', ar: 'ظهر', el: 'πίσω' },
  bag: { en: 'bag', ar: 'حقيبة', km: 'កាបូប', aliases: ['شنطة', 'حقيبة ظهر'] },
  bed: { en: 'bed', ar: 'سرير', km: 'គ្រែ', aliases: ['فراش'] },
  being_chased: { en: 'being chased', ar: 'مطاردة', el: 'κυνηγημένος', lt: 'bėgamas', aliases: [' chased', 'مطارد', 'هرب'] },
  belly: { en: 'belly', ar: 'بطن', km: 'ពោះ', aliases: ['بطن'] },
  bird: { en: 'bird', ar: 'طائر', km: 'បក្សី', aliases: ['عصفور', 'طائر'] },
  blood: { en: 'blood', ar: 'دم', km: 'ឈាម', lt: 'kraujas', aliases: ['دماء'] },
  bone: { en: 'bone', ar: 'عظم', el: 'οστό', aliases: ['عظام'] },
  book: { en: 'book', ar: 'كتاب', km: 'សៀវភៅ', lt: 'knyga', aliases: ['مصحف', 'قرآن'] },
  bridge: { en: 'bridge', ar: 'جسر', el: 'γέφυρα', lt: 'tiltas' },
  bus: { en: 'bus', ar: 'حافلة', el: 'λεωφορείο', km: 'ឡានក្រុង', aliases: ['باص', 'اتوبيس'] },
  candle: { en: 'candle', ar: 'شمعة', km: 'ទៀន', lt: 'žvakė', aliases: ['شموع'] },
  car: { en: 'car', ar: 'سيارة', km: 'រថយន្ត', lt: 'automobilis', aliases: ['عربية', 'سيارة'] },
  car_accident: { en: 'car accident', ar: 'حادث سيارة', km: 'គ្រោះថ្នាក់ចរាចរណ៍', lt: 'avarija', aliases: ['حادث', 'تصادم'] },
  cat: { en: 'cat', ar: 'قطة', el: 'γάτα', km: 'ឆ្មា', aliases: ['قطة', 'هر'] },
  chest: { en: 'chest', ar: 'صدر', el: 'στήθος', km: 'ទ្រូង', lt: 'krūtinė', aliases: ['صدر'] },
  child: { en: 'child', ar: 'طفل', el: 'παιδί', lt: 'va', aliases: ['ولد', 'بنت'] },
  clock: { en: 'clock', ar: 'ساعة', el: 'ρολόι', lt: 'laikrodis', aliases: ['ساعة'] },
  clothes: { en: 'clothes', ar: 'ملابس', el: 'ρούχα', km: 'សម្លៀកបំពាក់', lt: 'drabužiai', aliases: ['ثياب', 'لبس'] },
  cloud: { en: 'cloud', ar: 'غيم', lt: 'debesis', aliases: ['سحابة', 'غيمة'] },
  crown: { en: 'crown', ar: 'تاج', km: 'មករា', aliases: ['عرش'] },
  crying: { en: 'crying', ar: 'بكاء', km: 'ស្រៀវ', lt: 'verkiantis', aliases: ['بكاء', 'دموع'] },
  dark: { en: 'dark', ar: 'ظلام', el: 'σκοτεινό', aliases: ['عتمة', 'ليل'] },
  dead_person: { en: 'dead person', ar: 'شخص ميت', lt: 'mirusysis', aliases: ['ميت', 'جثة'] },
  death: { en: 'death', ar: 'موت', el: 'θάνατος', km: 'មរណៈ', aliases: ['موت', 'وفاة'] },
  death_family: { en: 'death of family', ar: 'موت أحد الأقارب', el: 'θάνατος της οικογένειας', km: 'ការស្លាប់របស់សមាជិកក្នុងគ្រួសារ', lt: 'sūnų mirtis', aliases: ['وفاة قريب'] },
  desert: { en: 'desert', ar: 'صحراء', el: 'ἔρημος', km: 'វេហា', lt: 'dykuma', aliases: ['صحراء'] },
  doctor: { en: 'doctor', ar: 'طبيب', el: 'ιατρός', km: 'វេជ្ជបណ្ឌិត', lt: 'gydytojas', aliases: ['دكتور'] },
  dog: { en: 'dog', ar: 'كلب', el: 'κύων', km: 'ស្រឡះ', lt: 'šuo', aliases: ['كلب'] },
  dog_attack: { en: 'dog attack', ar: 'هجوم كلب', el: 'προσβολή σκύλου', lt: 'šypsos atakos', aliases: ['عضة كلب'] },
  door: { en: 'door', ar: 'باب', el: 'θύρα', km: 'ទ្វារ', lt: 'durys', aliases: ['باب'] },
  ear: { en: 'ear', ar: 'أذن', el: 'ὦτις', lt: 'ausis', aliases: ['أذن'] },
  earthquake: { en: 'earthquake', ar: 'زلزال', el: 'σεισμός', km: 'កម្ដៅដី', lt: 'žemės drebėjimas', aliases: ['هزة أرضية'] },
  egg: { en: 'egg', ar: 'بيضة', el: 'αυγό', km: 'ពង', lt: 'kiaušinis', aliases: ['بيض'] },
  elbow: { en: 'elbow', ar: 'كوع', el: 'αγκών', km: 'កន្សោម', lt: 'alkūnis' },
  exam: { en: 'exam', ar: 'امتحان', el: 'εξέταση', km: 'ការប្រឡង', lt: 'egzaminas', aliases: ['اختبار', 'test'] },
  eye: { en: 'eye', ar: 'عين', el: 'ὀφθαλμός', km: 'ភ្នែក', lt: 'akis', aliases: ['عين', 'عيون'] },
  falling: { en: 'falling', ar: 'سقوط', km: 'ធ្លាក់', lt: 'kritimas', aliases: ['يسقط', 'سقوط'], el: 'πτώση'},
  father: { en: 'father', ar: 'أب', el: 'πατήρ', lt: 'tėvas', aliases: ['أب', 'والد'] },
  fighting: { en: 'fighting', ar: 'قتال', el: 'μάχη', km: 'ការប្រយុទ្ធ', lt: 'kovos', aliases: ['شجار', 'عراك'] },
  finger: { en: 'finger', ar: 'إصبع', el: 'δάχτυλο', km: 'ម្រា', lt: 'pirštas', aliases: ['أصابع'] },
  fire: { en: 'fire', ar: 'نار', el: 'πῦρ', km: 'អគ្គិភ័យ', lt: 'ugnis', aliases: ['حريق', 'نار'] },
  fire_burn: { en: 'fire / burn', ar: 'حريق أو حرق', el: 'κάψιμο', km: 'ដុត', lt: 'uždegimas / degimas', aliases: ['حرق'] },
  fish: { en: 'fish', ar: 'سمكة', el: 'ψάρι', km: 'ត្រី', lt: 'žuvis', aliases: ['سمك'] },
  flood: { en: 'flood', ar: 'فيضان', el: 'κατακλυσμός', km: 'ទឹកជំនន់', lt: 'povėsis', aliases: ['غرق'] },
  flower: { en: 'flower', ar: 'زهرة', el: 'άνθος', km: 'ផ្កា', lt: 'gėlė', aliases: ['وردة', 'زهور'] },
  flying: { en: 'flying', ar: 'طيران', el: 'πτήσιμον', km: 'ហោះ', lt: 'skraidymas', aliases: ['يطير', 'تحليق'] },
  flying_high: { en: 'flying high', ar: 'طيران عالٍ', km: 'ហោះហើរខ្ពស់', lt: 'skrendant aukštai', aliases: ['ارتفاع'] },
  food: { en: 'food', ar: 'طعام', el: 'τροφή', km: 'អាហារ', lt: 'maistas', aliases: ['أكل', 'وجبة'] },
  foot: { en: 'foot', ar: 'قدم', el: 'πούς', km: 'ហ្វីត', lt: 'pėda', aliases: ['أقدام', 'رجل'] },
  forest: { en: 'forest', ar: 'غابة', el: 'δάσος', km: 'ព្រៃ', lt: 'miškas', aliases: ['غابة'] },
  friend: { en: 'friend', ar: 'صديق', el: 'φίλος', km: 'មិត្ត', lt: 'draugas', aliases: ['صديق', 'صديقة'] },
  ghost: { en: 'ghost', ar: 'شبح', el: 'φάντασμα', km: 'ខ្មោច', lt: 'vaiduoklis', aliases: ['جن', 'روح'] },
  gold: { en: 'gold', ar: 'ذهب', el: 'χρυσός', km: 'មាស', lt: 'auksas', aliases: ['ذهب'] },
  gun: { en: 'gun', ar: 'مسدس', el: 'όπλο', km: 'កាំភ្លើង', lt: 'ginklas', aliases: ['سلاح', 'بندقية', 'رصاص'] },
  hair: { en: 'hair', ar: 'شعر', el: 'τρίχωμα', km: 'សក់', lt: 'plaukai', aliases: ['شعر'] },
  hand: { en: 'hand', ar: 'يد', el: 'χειρ', km: 'ដៃ', lt: 'rankas', aliases: ['يدين', 'كف'] },
  heart: { en: 'heart', ar: 'قلب', el: 'καρδιά', km: 'បេះដូង', lt: 'širdis', aliases: ['قلب'] },
  horse: { en: 'horse', ar: 'حصان', el: 'ίππος', km: 'សេះ', lt: 'arklys', aliases: ['حصان'] },
  hospital: { en: 'hospital', ar: 'مستشفى', el: 'νοσοκομείο', km: 'មន្ទីរពេទ្យ', lt: 'ligoninė', aliases: ['مشفى'] },
  house: { en: 'house', ar: 'بيت', el: 'οἶκος', km: 'ផ្ទះ', lt: 'namai', aliases: ['منزل', 'بيت'] },
  house_old: { en: 'old house', ar: 'بيت قديم', el: 'παλιό σπίτι', km: 'ផ្ទះចាស់', lt: 'senas namas', aliases: ['منزل قديم'] },
  injection: { en: 'injection', ar: 'حقنة', km: 'ការចាក់', aliases: ['إبرة'], el: 'ένεση'},
  island: { en: 'island', ar: 'جزيرة', el: 'νησί', km: 'កោះ', lt: 'salos', aliases: ['جزيرة'] },
  key: { en: 'key', ar: 'مفتاح', el: 'κλειδί', km: 'គន្លឹះ', lt: 'raktas', aliases: ['مفتاح', 'مفاتيح'] },
  king: { en: 'king', ar: 'ملك', el: 'βασιλεύς', km: 'ព្រះរាជា', lt: 'karalius', aliases: ['ملك'] },
  kissing: { en: 'kissing', ar: 'قُبلة', el: 'φιλί', km: 'បង្គំ', lt: 'bučiniai', aliases: ['قبلة', 'تقبيل'] },
  knee: { en: 'knee', ar: 'ركبة', el: 'γόνυ', km: 'ជង្រង', lt: 'kūnas', aliases: ['ركبة'] },
  knife: { en: 'knife', ar: 'سكين', el: 'μαχαίρι', km: 'កាំម្ជន', lt: 'peilis', aliases: ['سكينة'] },
  laughing: { en: 'laughing', ar: 'ضحك', el: 'γελῶν', km: 'ញើស', lt: 'juokiantis', aliases: ['ضحك'] },
  leg: { en: 'leg', ar: 'ساق', el: 'σκέλος', km: 'ជើង', lt: 'šlaunis', aliases: ['ساقين', 'رجل'] },
  light: { en: 'light', ar: 'ضوء', el: 'φως', km: 'ភ្លើង', aliases: ['نور', 'إضاءة'] },
  lion: { en: 'lion', ar: 'أسد', el: 'λέοντας', km: 'ក្រហម', lt: 'liutas', aliases: ['أسد'] },
  losing_teeth: { en: 'losing teeth', ar: 'سقوط الأسنان', el: 'χάνονται τα οδόντα', km: 'ចាត់ទំនាក់ទំនង', lt: 'įsikartojantys dantai', aliases: ['تساقط الأسنان'] },
  market: { en: 'market', ar: 'سوق', el: 'παρασκευή', km: 'ផ្សេងៗ', lt: 'parduotuvė', aliases: ['سوق'] },
  marriage: { en: 'marriage', ar: 'زواج', el: 'γάμος', km: 'ស្នេហា', lt: 'sventinė', aliases: ['عرس', 'زواج'] },
  marriage_broken: { en: 'broken marriage', ar: 'زواج منهار', el: 'σπάσιμο γάμος', km: 'ប្រឹក្សាស្រ្រីបាត់ការណ៍', lt: 'pajėgos nusikaltimas', aliases: ['طلاق'] },
  medicine: { en: 'medicine', ar: 'دواء', el: 'Ιατρική', km: 'ថ្នាក់ពេទ្យ', aliases: ['علاج'], lt: 'vaistas'},
  mirror: { en: 'mirror', ar: 'مرآة', km: 'ការកែសិក្សា', lt: 'lengtelis', aliases: ['مرآة'] },
  money: { en: 'money', ar: 'مال', el: 'χρήματα', km: 'លុយ', lt: 'pinigai', aliases: ['نقود', 'فلوس', 'دراهم'] },
  money_lost: { en: 'lost money', ar: 'مال مفقود', el: 'χάσει χρήματα', km: 'ចាស់កាន់ស្រាប់ការបានចាស់កាន់', lt: 'prarasti pinigus', aliases: ['سرقة مال'] },
  money_steal: { en: 'stolen money', ar: 'سرقة مال', el: 'κλέβομαι χρήματα', km: 'សង្ក្រាមស៊ីនដែលចាក់ចាស់', lt: 'suklioti pinigai', aliases: ['سرقة'] },
  moon: { en: 'moon', ar: 'قمر', el: 'Σελήνη', km: 'ចិត្ត', lt: 'mėnulis', aliases: ['قمر', 'بدر'] },
  moon_eclipse: { en: 'moon eclipse', ar: 'خسوف', el: 'Σελήνη Σκιές', aliases: ['خسوف قمر'] },
  mother: { en: 'mother', ar: 'أم', el: 'μητήρ', km: 'ម៉ែ', lt: 'motina', aliases: ['أم', 'والدة'] },
  motorcycle: { en: 'motorcycle', ar: 'دراجة نارية', el: 'μητάτορ (míttator)', km: 'យន្តករណ៍', lt: 'motociklas', aliases: ['موتوسيكل'] },
  mountain: { en: 'mountain', ar: 'جبل', el: 'βουνό (vouno)', km: 'ភ្នំពេញ', lt: 'kulisas', aliases: ['جبل'] },
  mouth: { en: 'mouth', ar: 'فم', el: 'στόμα', km: 'ក្រាន់', aliases: ['فم'], lt: 'burna'},
  naked: { en: 'naked', ar: 'عراة', el: 'γυμνός (gymnós)', aliases: ['عري', 'عاري'], km: 'នាត់ពាក់'},
  neck: { en: 'neck', ar: 'رقبة', el: 'το τραχήλιον', aliases: ['عنق'], km: 'កាត់'},
  nose: { en: 'nose', ar: 'أنف', el: 'πρόσωπο', aliases: ['أنف'], km: 'ស្រមុង'},
  nurse: { en: 'nurse', ar: 'ممرضة', el: 'παιδοτριφή', km: 'គ្រីធានី', aliases: ['ممرض'] },
  ocean: { en: 'ocean', ar: 'محيط', el: 'θάλασσα', km: 'កាន់កំពូន', aliases: ['محيط'] },
  phone: { en: 'phone', ar: 'هاتف', el: 'τηλέφωνο', km: 'ទូរស័ព្ទ', lt: 'telefonas', aliases: ['جوال', 'موبايل', 'تليفون'] },
  poison: { en: 'poison', ar: 'سم', km: 'ក្រោមក្រហម', aliases: ['سم'], el: 'δηλητήριο'},
  police: { en: 'police', ar: 'شرطة', el: 'Αστυνομία', km: 'ការកែវក្រាន់ការងារ', lt: 'policija', aliases: ['بوليس', 'شرطي'] },
  pregnancy: { en: 'pregnancy', ar: 'حمل', el: 'γravida (γravida)', km: 'ការការក្រោងក្រោនក្រោន', lt: 'būdinklis', aliases: ['حامل', 'حمل'] },
  pregnancy_test: { en: 'pregnancy test', ar: 'اختبار حمل', el: 'γravida test (γravida test)', lt: 'gravidumo bandymas', aliases: ['تحليل حمل'] },
  prison: { en: 'prison', ar: 'سجن', el: 'φωτιά (fotiá)', lt: 'katorga', aliases: ['حبس'] },
  queen: { en: 'queen', ar: 'ملكة', el: 'βασιλίσσα', lt: 'královė', aliases: ['ملكة'] },
  rain: { en: 'rain', ar: 'مطر', el: 'βροχή', km: 'ភាព (pheaap)', lt: 'uodėnys', aliases: ['مطر'] },
  ring: { en: 'ring', ar: 'خاتم', el: 'χρυσός', km: 'រង្វាំង', lt: 'keltas', aliases: ['خاتم'] },
  road: { en: 'road', ar: 'طريق', el: 'δρόμος', km: 'ផ្លូវក្រោម (គីឡូម)', lt: 'kelias', aliases: ['شارع'] },
  running: { en: 'running', ar: 'جري', el: 'τρέχω', km: 'ការចាកចេញចុំង្វាន់ការចាន់ការង្កាត់', lt: 'eikinėjimas', aliases: ['ركض'] },
  scar: { en: 'scar', ar: 'ندبة', aliases: ['أثر'] },
  school: { en: 'school', ar: 'مدرسة', aliases: ['مدرسة'] },
  sea: { en: 'sea', ar: 'بحر', aliases: ['بحر'] },
  shoe: { en: 'shoe', ar: 'حذاء', aliases: ['حذاء', 'جزمة'] },
  shopping: { en: 'shopping', ar: 'تسوق', aliases: ['تسوق'] },
  shoulder: { en: 'shoulder', ar: 'كتف', aliases: ['كتف'] },
  skin: { en: 'skin', ar: 'جلد', aliases: ['بشرة'] },
  smoke: { en: 'smoke', ar: 'دخان', aliases: ['تدخين'] },
  snake: { en: 'snake', ar: 'ثعبان', aliases: ['أفعى', 'حية', 'serpiente', 'serpent', 'schlange', 'cobra', 'viper'] },
  snake_bite: { en: 'snake bite', ar: 'لدغ ثعبان', aliases: ['لدغ'] },
  snake_many: { en: 'many snakes', ar: 'ثعابين كثيرة', aliases: ['افاعي'] },
  snow: { en: 'snow', ar: 'ثلج', aliases: ['ثلج'] },
  spider: { en: 'spider', ar: 'عنكبوت', aliases: ['عنكبوت'] },
  stairs: { en: 'stairs', ar: 'سلالم', aliases: ['درج'] },
  star: { en: 'star', ar: 'نجمة', aliases: ['نجمة', 'نجوم'] },
  storm: { en: 'storm', ar: 'عاصفة', aliases: ['رياح'] },
  stranger: { en: 'stranger', ar: 'غريب', aliases: ['شخص غريب'] },
  sun: { en: 'sun', ar: 'شمس', aliases: ['شمس'] },
  sun_rise: { en: 'sunrise', ar: 'شروق الشمس', aliases: ['فجر'] },
  surgery: { en: 'surgery', ar: 'عملية جراحية', aliases: ['عملية'] },
  teeth: { en: 'teeth', ar: 'أسنان', aliases: ['سن', 'أسنان'] },
  teeth_fall: { en: 'teeth falling', ar: 'سقوط الأسنان', aliases: ['تساقط الأسنان'] },
  teeth_falling: { en: 'teeth falling', ar: 'سقوط الأسنان', aliases: ['تساقط الأسنان'] },
  thief: { en: 'thief', ar: 'لص', aliases: ['سرقة'] },
  tongue: { en: 'tongue', ar: 'لسان', aliases: ['لسان'] },
  tornado: { en: 'tornado', ar: 'إعصار', aliases: ['زوبعة'] },
  train: { en: 'train', ar: 'قطار', aliases: ['قطار'] },
  tree: { en: 'tree', ar: 'شجرة', aliases: ['شجرة'] },
  tree_dead: { en: 'dead tree', ar: 'شجرة ميتة', aliases: ['شجرة يابسة'] },
  wallet: { en: 'wallet', ar: 'محفظة', aliases: ['محفظة'] },
  war: { en: 'war', ar: 'حرب', aliases: ['قتال'] },
  water: { en: 'water', ar: 'ماء', aliases: ['ماء', 'بحر', 'نهر'] },
  water_drink: { en: 'drinking water', ar: 'شرب الماء', aliases: ['ماء'] },
  water_flood: { en: 'water flood', ar: 'فيضان', aliases: ['غرق'] },
  weapon: { en: 'weapon', ar: 'سلاح', aliases: ['سلاح'] },
  wedding: { en: 'wedding', ar: 'زفاف', aliases: ['عرس', 'زواج'] },
  winning: { en: 'winning', ar: 'فوز', aliases: ['نجاح'] },
  wound: { en: 'wound', ar: 'جرح', aliases: ['جراح'] },
};
